// HMGS Soru Bankası Part 4 - Eksik dersler 10'a tamamlanıyor (İlk Kısım)
const questions4 = [
// ===== Ceza Muhakemesi Usulü (5 ek) =====
["Ceza Muhakemesi Usulü","CMK'ya göre şüphelinin ifade alımı sırasında müdafi bulunması hangi durumda zorunludur?","Her durumda","Sadece cinayet suçlarında","Alt sınırı 5 yıldan fazla hapis cezasını gerektiren suçlarda","Yalnızca çocuk şüphelilerde","Yalnızca yabancı uyruklu şüphelilerde","C","CMK m.150/3'e göre alt sınırı 5 yıldan fazla hapis cezasını gerektiren suçlardan dolayı yapılan soruşturma ve kovuşturmada şüphelinin/sanığın müdafii yoksa barodan bir müdafi görevlendirilmesi zorunludur.","Zorunlu Müdafilik: Alt sınırı 5 yıldan fazla hapis gerektiren suçlar. Şüpheli/sanık çocuk, kendisini savunamayacak derecede malul veya sağır ve dilsiz ise istemi aranmaksızın müdafi atanır."],
["Ceza Muhakemesi Usulü","İddianamenin mahkemeye verilmesi üzerine mahkeme iddianameyi ne kadar sürede incelemelidir?","7 gün","10 gün","15 gün","30 gün","1 ay","C","CMK m.174'e göre mahkeme, iddianameyi ve soruşturma evrakını 15 gün içinde inceler. İade veya kabul kararı vermezse iddianame kabul edilmiş sayılır.","İddianamenin İadesi Süresi: Mahkemeye verildikten sonra mahkemenin 15 gün inceleme süresi vardır. Bu süre dolunca eksiklik yoksa iade edilemez, kabul kararı verilmiş sayılır."],
["Ceza Muhakemesi Usulü","Aşağıdakilerden hangisi adli kontrol tedbirlerinden biri değildir?","Yurt dışına çıkamamak","Hakim tarafından belirlenen yerlere belirtilen sürelerde düzenli olarak başvurmak","Silah bulunduramamak","Ev hapsi (konutunu terk etmemek)","Zorunlu kamu hizmetinde çalışmak","E","CMK m.109'a göre zorunlu kamu hizmetinde çalışmak adli kontrol tedbiri değil, hapis cezası seçenek yaptırımıdır. Diğerleri ise adli kontrol tedbirleridir.","Adli Kontrol (CMK m.109): Tutuklama sebepleri varlığında, şüpheli/sanığın özgürlüğünün daha az kısıtlanmasıdır. Şartları: Yurt dışına çıkış yasağı, ev hapsi, belirli yerlere gitmekten yasaklanma, imza atmak vb. Tutuklamanın istisnasıdır."],
["Ceza Muhakemesi Usulü","Yakalama kime karşı yapılır?","Sadece sanık","Bilirkişi","Tanık","Sadece hükümlü","Şüpheli veya Hükümlü","E","CMK m.90'a göre yakalama kararı veya emri şüpheli (soruşturma) veya sanık (kovuşturma/hükümlü) hakkında verilebilir. Herkesin yakalama hakkı, meşhud cürüm (suçüstü) halinde vardır.","Yakalama: Gecikmesinde sakınca bulunan hallerde veya suçüstü durumunda kolluk güçleri veya herkes (suçüstü) yakalama yapabilir. Yakalanan kişiye derhal hakları bildirilir."],
["Ceza Muhakemesi Usulü","CMK'da iletişimin tespiti, dinlenmesi ve kayda alınması kararı kim tarafından verilir?","Kolluk amiri","Cumhuriyet Savcısı","Sulh Ceza Hakimi veya Ağır Ceza Mahkemesi","Vali","Adalet Bakanı","C","CMK m.135'e göre iletişimin tespiti, dinlenmesi ve kayda alınmasına hakim karar verir. Gecikmesinde sakınca bulunan hallerde savcı karar verebilir, 24 saat içinde hakim onayına sunulur.","İletişimin Dinlenmesi: Hakim kararıyla yapılır. Başka yolla delil elde etme imkanının olmaması, kuvvetli suç şüphesinin varlığını gösteren somut delillerin olması ve katalog suçlardan (örn: göçmen kaçakçılığı, kasten öldürme) birinin olması gerekir."],

// ===== Hukuk Yargılama Usulü (5 ek) =====
["Hukuk Yargılama Usulü","HMK'ya göre taraf ehline sahip olabilmek için Medeni Hukuktaki hangi ehliyete sahip olmak gerekir?","Fiil ehliyeti","Hak ehliyeti","Dava ehliyeti","Seçme ehliyeti","Ayırt etme gücü","B","HMK m.50'ye göre taraf ehliyeti, medeni hukuktaki hak ehliyetine karşılık gelir. Hak ehliyeti olan her gerçek veya tüzel kişi davada taraf olabilir.","Taraf Ehliyeti ve Dava Ehliyeti: Taraf ehliyeti (davacı/davalı olabilme) = Hak ehliyeti (doğumla/tüzel kişilik kazanımıyla başlar). Dava ehliyeti (davayı yürütebilme) = Fiil ehliyeti (erginlik, ayırt etme gücü, kısıtlı olmama)."],
["Hukuk Yargılama Usulü","Davaya müdahale (fer'i müdahale) hangi aşamaya kadar yapılabilir?","Ön inceleme aşamasına kadar","Tahkikat sona erinceye kadar","Hüküm kesinleşinceye kadar","Sadece dava dilekçesi aşamasında","Duruşma safhasının sonuna kadar","B","HMK m.66'ya göre, üçüncü kişi davayı kazanmasında hukuki yararı bulunan taraf yanında ve ona yardımcı olmak amacıyla tahkikat sona erinceye kadar davaya fer'i müdahil olarak katılabilir.","Fer'i Müdahale: Üçüncü kişinin hukuki yararı doğrultusunda, bir taraf yanında, onun haklarını savunmasına yardımcı olmasıdır. Tek başına işlem yapamaz, asıl tarafın kararlarına aykırı davranamaz. Tahkikat sonuna kadar istenebilir."],
["Hukuk Yargılama Usulü","Sulh hukuk mahkemesinin görev alanına giren dava hangisidir?","Nafaka davası (boşanma neticesinde olmayan)","Ticari davalar","Vesayet davaları","Cebri icra ihalelerinin feshi davası","Tüketici davaları","C","HMK m.4'e göre vesayet ve kayyımlık gibi sulh hukuk mahkemesi konularıdır. Diğer çekişmesiz yargı işleri (istisna yoksa) sulhe aittir. Diğer davalar Asliye, Aile, Tüketici vb. mahkemelerin görevindedir.","Sulh Hukuk Mahkemesinin Görevleri: Miktar gözetilmeksizin; Kira ilişkisinden doğan tüm uyuşmazlıklar, paylaştırma davaları, zilyetliğin korunması davaları, vesayet işleri ve diğer kanunların belirttiği davalar sulh hukuk mahkemesinde görülür."],
["Hukuk Yargılama Usulü","HMK'ya göre yemin teklifi ne demektir ve kime yapılır?","Hakimin karar vermesi","Taraflardan birinin davasını ispat için karşı tarafa yemin ettirmesi","Şahidin edeceği yemin","Bilirkişinin tarafsızlık yemini","Avukatın meslek yemini","B","HMK m.225'e göre yemin, taraflardan birinin iddia ettiği ancak ispatlayamadığı vakıayı karşı tarafın 'doğru olduğuna veya olmadığına' yemin etmesini istemesidir. Taraf bizzat yemin eder.","Yemin Delili: Kesin bir ispat aracıdır. Diğer taraf yemin ederse yemin eden lehine karar verilir. Yeminden kaçınırsa yemin teklif eden vakıayı ispat etmiş sayılır. Kendinden kaynaklanmayan olay veya fiil yemin konusu olamaz."],
["Hukuk Yargılama Usulü","Davanın geri alınması hangi şarta bağlıdır?","Hakimin rızasına","Karşı tarafın açık muvafakatine (rızasına)","Sadece davacının iradesine","Savcının onayına","İstinaf mahkemesi iznine","B","HMK m.123'e göre davacı, hüküm kesinleşinceye kadar davasını ancak karşı tarafın açık muvafakati ile geri alabilir. (Feragatten farklıdır, feragat tek taraflıdır).","Davanın Geri Alınması vs Feragat: Feragat, davacının talep sonucundan vazgeçmesidir (karşı taraf rızası gerekmez). Davanın geri alınması ise davanın hiç açılmamış sayılmasını sağlar ancak karşı tarafın rızası zorunludur."],

// ===== İcra ve İflas Hukuku (5 ek) =====
["İcra ve İflas Hukuku","Aşağıdakilerden hangisi kambiyo senetlerine özgü haciz yoluyla takibin özelliklerinden biridir?","İtiraz takibi durdurur","Sadece bono, poliçe veya çek olması şartı aranır","Ödeme süresi 7 gündür","Teminatsız ihtiyati haciz istenemez","Her borçlu itirazda bulunamaz","B","İİK m.167'ye göre kambiyo senetlerine (çek, poliçe, bono) özgü haciz yoluna başvurabilmek için alacağın bu senetlerden birine müstenit olması şarttır.","Kambiyo Senetlerine Özgü Haciz: Alacak bir kambiyo senedine dayanmalıdır. Ödeme emrine itiraz süresi 5 gün, ödeme süresi 10 gündür. İtiraz icra mahkemesine yapılır ve satış dışında takibi durdurmaz."],
["İcra ve İflas Hukuku","İflas tasfiyesinde masa alacaklıları ile iflas alacaklıları arasındaki fark nedir?","Masa alacaklıları iflastan sonra, iflas alacaklıları iflastan önce doğan alacakları ifade eder","Fark yoktur","Masa alacaklıları devlet alacaklarıdır","İflas alacaklıları yurt dışındadır","Masa alacaklıları rehinli alacaklılardır","A","Masa alacakları iflas açıldıktan sonra masanın ve iflas idaresinin yaptığı işlemler sonucunda doğan borçlardır, önceliklidir. İflas alacaklıları ise borçlunun iflas açılmadan önceki alacaklılarıdır.","Masa ve İflas Alacakları: İflas alacaklıları iflas masasına kaydedilir ve paraya çevirme sonrası sıraya göre ödenir. Masa alacakları ise tasfiye masraflarıdır (örn: depo kirası, vergi) ve ilk tasfiye edilen para ile hemen ve tam ödenir."],
["İcra ve İflas Hukuku","Rehnin paraya çevrilmesi yoluyla takipte borçlunun 'borcum yoktur' itirazı ne kadar sürer?","3 gün","5 gün","7 gün","10 gün","15 gün","C","İİK m.147'ye göre ilamsız rehnin paraya çevrilmesi takiplerinde borçlu 7 gün içinde ödeme emrine itiraz edebilir (genel haciz yoluyla aynıdır).","Rehnin Paraya Çevrilmesi Yoluyla Takip: Alacaklı alacağı rehinle temin edilmişse, kural olarak öncelikle rehnin paraya çevrilmesi yoluna başvurmak zorundadır. İlamsız takipte ödeme 15 gün, itiraz 7 gündür. İlamlı takipte icra emri gönderilir (itiraz edilemez)."],
["İcra ve İflas Hukuku","İhalenin feshi davası kime karşı ve nerede açılır?","İcra dairesine - Asliye Hukuk Mahkemesi","Alıcıya veya satış isteyen alacaklıya - İcra Mahkemesi","Borçluya - İhale Salonu","Devlete - İdare Mahkemesi","Bankaya - Tüketici Mahkemesi","B","İİK m.134'e göre ihalenin feshi davası icra mahkemesinde, ihaleyi alan kişi veya kendisi, satış talep eden, borçlu vb. ilgililerce açılabilir ve dava karşı tarafa husumet yöneltilerek görülür.","İhalenin Feshi (İİK m.134): Tebligat usulsüzlüğü, ihaleye fesat karıştırılması gibi hallerde, ihalenin feshi ihale tarihinden itibaren en geç 7 gün içinde icra mahkemesinden istenir. Feshi gerektiren sebep daha sonra öğrenilse de ihaleden itibaren 1 yılı geçemez."],
["İcra ve İflas Hukuku","Aşağıdakilerden hangisi doğrudan doğruya iflas hallerinden (takipsiz iflas) biridir?","Borçlunun haciz sırasında itiraz etmesi","Borçlunun sadece bir alacaklısına ödeme yapmamış olması","Borçlunun yerleşim yerini gizlemesi veya alacaklıları zarara sokmak kastıyla kaçması","Senet ödemesinde temerrüde düşmesi","Mahkeme kararını temyiz etmesi","C","İİK m.177/1'e göre borçlunun kaçması veya alacaklıları zarara sokmak maksadıyla hileli muamelelerde bulunması evvelceden bir takibe hacet kalmaksızın doğrudan doğruya iflas davası açılmasına imkan tanır.","Doğrudan İflas (Takipsiz İflas): Önceden icra takibi yapılmaksızın asliye ticaret mahkemesinde doğrudan açılan iflas davasıdır. Borçlunun ödemelerini tatil etmesi, kaçması veya ilamlı icra takibine rağmen borcu ödememesi sebeplerdendir."],

// ===== İş ve Sosyal Güvenlik Hukuku (5 ek) =====
["İş ve Sosyal Güvenlik Hukuku","İş sözleşmesinin feshi sırasında verilmesi gereken İhbar Süreleri 1,5 ile 3 yıl arası kıdemi olan işçi için kaç haftadır?","2 hafta","4 hafta","6 hafta","8 hafta","10 hafta","C","4857 s. İş Kanunu m.17'ye göre ihbar süreleri: 6 aydan az ise 2 hafta, 6 ay-1.5 yıl 4 hafta, 1.5-3 yıl 6 hafta, 3 yıldan fazla 8 haftadır.","İhbar Önel Süreleri (İK m.17): Çalışma süresi → İhbar Süresi (Hafta). 0-6 ay → 2 hafta, 6 ay-1.5 yıl → 4 hafta, 1.5 yıl-3 yıl → 6 hafta, 3 yıl ve daha fazla → 8 hafta. Uyulmazsa ihbar tazminatı ödenir."],
["İş ve Sosyal Güvenlik Hukuku","Gece çalışma süresi en fazla kaç saattir?","6 saat","7.5 saat","8.5 saat","10 saat","11 saat","B","İş K. m.69'a göre, çalışma hayatında 'gece' en geç saat 20.00'de başlayarak en erken saat 06.00'ya kadar geçen ve her halde en fazla 11 saat süren dönemdir ve gece çalışmaları en fazla 7.5 saat olabilir.","Gece Çalışmaları: Saat 20:00 ile 06:00 arası döneme işaret eder (11 saati geçmez). İşçilerin gece çalışma süresi günlük 7.5 saati aşamaz (bazı sektörler (örn: sağlık, koruma) işçi onayı ile aşabilir). Kadın işçiler gece postalarında 7.5 saatten fazla çalıştırılamazlar."],
["İş ve Sosyal Güvenlik Hukuku","Haftalık normal çalışma süresi İş Kanununa göre en çok kaç saattir?","35","40","45","48","50","C","İş K. m.63'e göre genel bakımdan haftalık normal çalışma süresi en çok 45 saattir. Taraflarca anlaşılmışsa bu süre, haftanın çalışılan günlerine, günde 11 saati aşmamak koşuluyla eşit olarak bölünür.","Normal ve Fazla Çalışma: Haftalık çalışma en fazla 45 saattir. Eşit/eşitsiz dağıtılabilir ama günlük çalışma 11 saati aşamaz. 45 saati geçen çalışma 'Fazla Çalışma'dır ve 1.5 katı (veya fazla sürelerle çalışma ise 1.25 katı) ücret ödenir."],
["İş ve Sosyal Güvenlik Hukuku","İşçiye kıdem tazminatı verilmesini gerektirmeyen fesih türü aşağıdakilerden hangisidir?","İşverenin ahlak ve iyi niyet kurallarına aykırılık (Md 25/2) sebebiyle haklı feshi","Kadın işçinin evlendiği tarihten itibaren 1 yıl içinde fesh etmesi","Erkek işçinin askerlik sebebiyle ayrılması","İşveren haksız nedenle feshetmesi","İşçinin haklı sebeple derhal feshi","A","1475 sayılı Kanun m.14'e göre kıdem tazminatı verilmeyen nadir hallerden biri (ve en önemlisi) işverenin, işçiyi İş Kanunu m.25/II (Ahlak ve İyiniyet kurallarına aykırılık, vs. devamsızlık) sebebiyle derhal ve haklı nedenle çıkarmasıdır.","Kıdem Tazminatına Hak Kazandıran Haller: En az 1 yıllık hizmet süresi gereklidir. İşçinin haklı feshi, işverenin ahlak (m25/2) dışı feshinden başka feshi (haksız feshi vb), ölüm, emeklilik, kadın işçinin 1 yıl içinde evlenmesi, muvazzaf askerlik kıdem tazminatı doğurur."],
["İş ve Sosyal Güvenlik Hukuku","SGK primlerinden sayılan 'Genel Sağlık Sigortası (GSS) primi' oranı yüzde kaçtır?","%5","%9","%11","%12,5","%20","D","5510 sayılı Kanun m.81'e göre Genel Sağlık Sigortası primi, prime esas kazancın %12,5'idir. Bunun %5'i sigortalı (işçi), %7,5'i işveren payıdır.","Sigorta Primi Oranları: Malullük Yaşlılık ve Ölüm Sig.: Toplam %20 (İşçi %9, İşveren %11). Genel Sağlık Sigortası: Toplam %12,5 (İşçi %5, İşveren %7,5). İşsizlik Sig.: Toplam %3 (İşçi %1, İşveren %2)."],

// ===== İdari Yargılama Usulü (5 ek) =====
["İdari Yargılama Usulü","Davaya müdahale (davaya katılma) talebini hangi usule göre ve süre içinde yapabilirsiniz?","60 gün","İlk savunmaya cevap verilene kadar","Karar verilene kadar HMK müdahale usulleri uygulanır","Cevap süresinde","30 gün","C","İYUK'ta müdahale özel olarak düzenlenmemiş, HMK'nın (Hukuk Muhakemeleri Kanunu) hükümleri kıyasen uygulanır (İYUK m.31). Tahkikat sonuna (İdari yargıda kural olarak dosya tekemmülü ile karar verilene) kadar müdahale talep edilebilir.","İdari Yargıda Kıyas (HMK Uygulaması İYUK m.31): Hakimin davaya bakmaktan memnuiyeti ve reddi, ehliyet, üçüncü şahısların davaya katılması (müdahale), davanın ihbarı, bilirkişi, keşif, haciz gibi konularda HMK kıyasen uygulanır."],
["İdari Yargılama Usulü","İdari yargıda ehliyet (menfaat) incelemesi iptal ve tam yargı davalarında nasıl farklılık gösterir?","İptal davasında menfaat ihlali, tam yargı davasında hak ihlali aranır","Her ikisinde de menfaat ihlali yeterlidir","Her ikisinde de hak ihlali aranır","Fark yoktur","İptal davasında hak ihlali, tam yargıda menfaat ihlali","A","İYUK m.2'ye göre İptal davalarında meşru, kişisel ve güncel bir \"menfaatinin ihlali\" yeterliyken, tam yargı (tazminat) davalarında davacının doğrudan \"hakkının (kişisel hakkının) ihlal\" edilmiş olması şarttır.","İdari Davalar ve Ehliyet: İptal Davası: İdari işlemin hukuka uygunluğunun denetimidir. Doğrudan zarar/maddi hak gerekmeyebilir ancak menfaat bağı olmalıdır. Tam Yargı Davası: Uğranılan bir zararın giderimidir, bu sebeple kişinin kendi hakkı zarar görmüş (ihlal edilmiş) olmalıdır."],
["İdari Yargılama Usulü","İdari yargıda idari işlemin iptali davası kaç alt nedene dayanabilir? (İptal nedenleri nelerdir?)","Yetki, şekil, sebep, konu","Sadece kanun dışılık","Yetki ve Şekil","Yetki, Şekil, Sebep, Konu Maksat (Amaç)","Şekil, Sebep, Karar","D","İYUK m.2/1-a'ya göre iptal davaları yetki, şekil, sebep, konu ve maksat yönlerinden biri ile hukuka aykırı oldukları ileri sürülerek iptalleri için açılan davalardır. İdare hukuku işlem unsurları aynı zamanda iptal davası nedenleridir.","İdari İşlemin Unsurları / İptal Nedenleri: Yetki: İşlemi yapan makam-kişi (zaman boyutlu dahil). Şekil: Usul, yöntem kuralları. Sebep: İşlemin yapılmasını zorunlu kılan itici güç (hukuki ve fiili neden). Konu: İşlemin yaratacağı hukuki sonuç. Maksat: Kamu yararı."],
["İdari Yargılama Usulü","Bir idari işlemin icra edilebilirliğini ertelemek için talep edilen 'Yürütmenin Durdurulması' kararına idare ne kadar sürede itiraz edebilir?","3 gün","7 gün","15 gün","30 gün","60 gün","B","İYUK m.27/7'ye göre yürütmenin durdurulması istemleri hakkında verilen kararlara karşı tebliğini izleyen günden itibaren 7 gün içinde, bölge idare mahkemesine (Danıştay kararları ise ilgili İDDK/VDDG'ye) itiraz edilebilir. İtiraz kararları kesindir.","Yürütmenin Durdurulması (YD): Karar verebilmek için iki şart birlikte gerçekleşmelidir: Telafisi güç zarar ve Açıkça hukuka aykırılık. YD kararına 7 gün içinde itiraz edilebilir, mercii itirazı 7 gün içinde inceler ve kararı kesindir."],
["İdari Yargılama Usulü","İdare Mahkemesinde dava kime karşı (davalı kim olacak şekilde) husumet yöneltilerek açılmalıdır?","Sadece İçişleri Bakanlığı","Bizzat işlemi yapan kamu görevlisine","Devlet veya TBMM'ye","İşlemi tesis eden idari mercii (kamu tüzel kişisine) veya bakanlığa","CİMER'e","D","İdari davalar ve özellikle iptal ile tam yargı davaları, hukuka aykırı işlemi yapan (veya yapması gerekirken yapmayan) işlemi tesis eden İdare'ye (kuruma/bakanlığa/belediyeye vb.) karşı açılır. Kamu görevlisine husumet yöneltilmez.","Husumet Yöneltme İYUK m.14/m.15: Davanın yanlış hasma tevcih edilmesi durumunda (husumet yokluğu/yanlış kişiyi dava etme), mahkeme davayı doğrudan reddetmez; re'sen hasım düzelterek (gerçek hasmı belirleyerek) tebligatı doğru idareye yapar."],

// ===== Anayasa Yargısı (5 ek) =====
["Anayasa Yargısı","Anayasa Mahkemesi Başkanı nasıl seçilir?","Cumhurbaşkanı atar","TBMM Genel Kurulu seçer","Kendi üyeleri arasından gizli oyla ve üye tam sayısının salt çoğunluğu ile seçilir","Yargıtay tarafından","En yaşlı üye başkan olur","C","AY m.146'ya göre Anayasa Mahkemesi üyeleri kendi aralarından gizli oyla ve üye tamsayısının salt çoğunluğu ile Mahkeme Başkanı ile İki Başkanvekilini belirler. Görev süreleri 4 yıldır, yeniden seçilebilirler.","AYM Yapısı: 15 üyedir (3 üye TBMM, 12 üye Cumhurbaşkanı seçer). Görev süresi 12 yıldır, tekrar seçilemezler (yaş haddi:65). Ancak başkanlık görevine seçilenler, mahkeme üyesi olduğu sürece (maksimum 4+4 vs) tekrar başkan seçilebilir."],
["Anayasa Yargısı","Kural denetimi olarak adlandırılan Soyut Norm Denetimi (İptal Davası) Anayasa Mahkemesinde hangi sürede açılmalıdır?","Resmi gazetede yayın tarihinden itibaren 10 gün ve 60 gün","Hemen","Cumhurbaşkanı veya grup dilediği zaman","Yayımı izleyen 6. aydan sonra","Kanun yasa tasarısı mecliste iken","A","AY m.151'e göre Anayasa Mahkemesinde doğrudan iptal davası açma hakkı, iptal edilecek kanunun vb. Resmi Gazetede yayımlanmasından başlayarak şekil bozukluğuna dayalı ise 10 gün, esas yönünden ise 60 gün sonra düşer.","İptal Davası Açma Süresi: Şekil bozukluğuna dayalı iptal istemleri yayımdan itibaren 10 gün içinde yapılır. Esas iptal talepleri veya KHK (günümüzde CBK) vb. için süre yayımdan itibaren 60 gündür."],
["Anayasa Yargısı","Somut norm denetimi esnasında AYM'nin ret kararı sonrası mahkeme aynı mesele için kaç yıl beklemek zorundadır?","1 Yıl","2 Yıl","5 Yıl","10 Yıl","Beklemez","D","AY m.152/4'e göre Anayasa Mahkemesinin işin esasına girerek verdiği red kararının Resmi Gazete’de yayımlanmasından sonra on yıl geçmedikçe, aynı kanun hükmünün Anayasaya aykırılığı iddiasıyla tekrar müracaatta bulunulamaz.","Somut Norm Denetimi İtiraz Yolu: Davaya bakan heyet yasanın anayasaya aykırı kanaatine varırsa itiraz yoluna giderek meseleyi AYM'ye taşır, duruşma bekler (Max 5 ay). Esasa ilişkin red çıkarsa 10 yıl o madde itiraz konusu yapılamaz."],
["Anayasa Yargısı","Siyasi Partilerin temelli kapatılması istemi kime yapılır, kim karar verir?","Yargıtay Cumhuriyet Başsavcısı AYM'de dava açar","Cumhurbaşkanı Meclise sunar","İçişleri Bakanlığı Danıştay'a","Dernekler masası Ağır Ceza'ya","Yüksek Seçim Kurulu AYM'ye","A","AY m.69'a göre Siyasi partilerin kapatılması davalarını açma ve yargılama: Yargıtay Cumhuriyet Başsavcısı tarafından açılır, Anayasa Mahkemesi de kesin karara bağlar.","Siyasi Parti Kapatma Şartları: Yargıtay Cumhuriyet Başsavcısının davası üzerine Anayasa Mahkemesi (15 üyeli kurul) toplantıya katılanların üçte iki (2/3) oy çokluğu ile karar verir. Temelli kapatılma veyahut kısmen/tamamen devlet yardımından yoksun bırakılma (hazine yardımı kesintisi) kararı verilebilir."],
["Anayasa Yargısı","Milletvekili düşürülmesi veya vekilliğin zevali işlemlerinden sonra iptali istenebilir mi? İstenirse nereye, kaç gün içinde?","Bölge idare mahkemesi, 30 gün içinde","Anayasa Mahkemesi'ne 7 gün içinde","Oylama tekrarı Meclis'te 5 gün içinde","YSK'ya 10 gün","İstenemez","B","AY m.85'e göre TBMM üyesi veya Meclis dışından başka bir milletvekili, yasama dokunulmazlığının kaldırılması veya vekilliğin düşmesi kararının iptali için on beş (7) gün içerisinde Anayasa Mahkemesi'ne başvurabilir. AYM 15 gün içinde kesin karara bağlar.","Yasama İptal İtiraz Hakkı: TBMM Kararı ile dokunulmazlığı kaldırılan veya meclisi mazeretsiz izinsiz bir ay içinde 5 birleşim günü gitmeyerek düşürülen milletvekili (m.84) bizzat kendi yahut meclisteki bir başka vekil tarafından 7 gün içinde AYM iptal davası açabilir (Karar 15 gün içinde çıkar)."],

// ===== Vergi Hukuku (5 ek) =====
["Vergi Hukuku","Aşağıdakilerden hangisi doğrudan vergilerin (gelir veya servet) kapsamına girmez?","Kurumlar Vergisi","Emlak Vergisi","Motorlu Taşıtlar Vergisi (MTV)","Özel Tüketim Vergisi (ÖTV)","Gelir Vergisi","D","ÖTV, işlemlere ve harcamalara (tüketime) dayalı olduğundan dolaylı vergidir. Doğrudan vergiler kazançlar (gelir, kurumlar) veya servet (emlak, motorlu taşıtlar, veraset) üzerinden alınır.","Türk Vergi Sistemi Vergileri: Gelir (Doğrudan): Gelir Vergisi (GV), Kurumlar Vergisi (KV). Servet (Doğrudan): MTV, Emlak Vergisi, Veraset ve İntikal Vergisi. Harcama/Tüketim (Dolaylı): KDV, ÖTV, Damga Vergisi, Gümrük Vergileri, BSMV."],
["Vergi Hukuku","Harçlar, şerefiyeler, harcamalara katılma payları ne tür gelirler arasında yer alır?","Bağış","Kredi/Borçlanma","Özel Gelirler","Kamu Gelirleri (Kamu Kaynağı)","Ceza gelirleri","D","Kamunun finansmanı vergi, resim, harç, parafiskal gelirler, teşebbüs-mamelek geliri ve borçlanma vb. ile sağlanır. Harçlar, şerefiyeler ve harcamaya katılma payları idareye has kamu kamu ekonomisi geliridir (Vergi benzeri).","Kamu Gelirleri ve Vergi Benzerleri: Harçlar, kamu hizmetinden doğrudan faydalananlardan ödenir (örn: tapu, yargı). Resim (Rüsum), izin belgesi karşılığı alınan tutarlardır. Şerefiye (Değerleme Resmi): Kamu altyapı hizmetiyle emlağın değerinin artışı sebebiyle 1 sefere mahsus alınan paralardır."],
["Vergi Hukuku","Aşağıdakilerden hangisi vergide 'Adalet' veya 'Eşitlik' ilkelerini karşılamak adına modern vergi kanunlarında uygulanan teknik bir özelliktir?","Muafiyet yerine tam mükellefiyet","Artan Oranlı Tarife (Müterakki, Azalan Vergi)","Tek Matrah (Maktu)","Dolaylı Vergilerin Yüksek Olması","Her yurttaştan 'Cizye ve Haraç' maktu alımı","B","Artan Oranlı veya Müterakki oran, Anayasadaki m.73; Vergi yükünün adaletli ve dengeli dağılımı (Mali güce göre vergi) esasını temel alan ve çok kazanandan yüksek oranda (%15,%20...%40) az kazanandan az vergi alma prensibidir.","Vergi Adaleti İlkeleri: Mali Güç İlkesi: Herkesin kamu giderlerini karşılamak üzere mali gücüne göre vergi yükümlüsü olmasıdır. Kişinin şahsi giderleri, medeni durumu ve engellilik gibi özelliklerinin dikkate alınmasıdır. Bu ilkenin araçları: Artan oranlı tarife, Muafiyet, İstisna ve Asgari Geçim İndirimi gibi tekniklerdir."],
["Vergi Hukuku","Evli/Nişanlı olan kişiler Vergi Hukukunda Müteselsil Sorumlu tutulabilirler mi? Hangi durumda?","Hayır asla tutulmaz","Evet, karı/koca müşterek gelirle birbirinin borcundan mesuldür","Kural olarak hayır (ancak miras varsa ölüm hali müteselsil bırakabilir)","Birlikte mükellef olunan her şeyde","Mal rejimi eşlere zorunlu olarak yükler","C","Vergi usulünde şahsi mükellefiyet kuraldır. Eşlerin birbirlerinin gelirlerinden kaynaklanan vergi borçlarına karşın mükellef olmaları ya da müteselsil sorumluluk taşımaları (veraset halleri ve borçlanmalar-iştirak hariç) söz konusu olamaz. (Her eşin kendi vergi levhası ve kişisel GV borcu şahsidir).","Kişisellik ve Müteselsil Sorumluluk: Vergi şahsidir. (İstisnalar: KDV yasal temsilcisinin sorumluluğu, Vergi Usul m.11 vergi kesen ve asıl mükellef sorumluluğu, Kurum Ortakları, Verasette varislerin borcu oranla ödemesi vs.)"],
["Vergi Hukuku","Türkiye'de ikamet etmeyen ve merkezi Türkiye'de olmayan ama buradan belli kazanç (Kira, menkul sermaye vs) sağlayan vergi öznelerine ne denir?","Tam Mükellef","Vatandaş","Daimi Mükellef","Dar Mükellef","Göçmen Mükellef","D","Türkiye'de yerleşmiş olmayan gerçek kişiler / Merkezleri Türkiye'de bulunmayan kurumlar sadece Türkiye içinde elde ettikleri kazanç ve iratlar üzerinden 'Dar Mükellefiyet' esaslarına göre vergi öderler.","Tam Mükellef vs Dar Mükellef: Tam Mükellef (İkamet Türkiye, Kurum MS (merkez veya Kanuni) Türkiye) hem Türkiye hem de Türkiye Dışı (Yurtiçi+Yurtdışı) tüm kazancı için vergilendirilir. Dar Mükellef sadece Tr'de elde edilen için vergilendirilir."]
];

module.exports = questions4;
