// HMGS Soru Bankası Part 3 - Eksik dersler tamamlanıyor (her ders min 5 soru)
const questions3 = [
// ===== HUKUK YARGILAMA USULÜ (HMK) - 5 yeni =====
["Hukuk Yargılama Usulü","HMK'ya göre dava şartlarından biri aşağıdakilerden hangisidir?","Teminat gösterilmesi","Görevli mahkemede dava açılması","Tanık dinlenmesi","Keşif yapılması","Bilirkişi raporu alınması","B","HMK m.114'e göre dava şartları: Türk mahkemelerinin yargı hakkı, yargı yolu, görev, kesin yetki, taraf ehliyeti, dava ehliyeti, dava takip yetkisi, vekil olma, davacının yatırması gereken gider avansı.","Dava Şartları (HMK m.114): Mahkeme dava şartlarını kendiliğinden araştırır. Dava şartı noksanlığı halinde dava usulden reddedilir. Görev, yargı yolu ve kesin yetki dava şartıdır."],
["Hukuk Yargılama Usulü","Basit yargılama usulüne tabi davalarda cevap süresi kaç haftadır?","1 hafta","2 hafta","4 hafta","1 ay","15 gün","B","HMK m.317'ye göre basit yargılama usulünde cevap süresi dava dilekçesinin tebliğinden itibaren 2 haftadır.","Yargılama Usulleri: Yazılı yargılama usulü: cevap süresi 2 hafta (uzatılabilir). Basit yargılama usulü: cevap süresi 2 hafta (uzatılamaz). Basit yargılama usulünde iddia ve savunma genişletilemez."],
["Hukuk Yargılama Usulü","HMK'ya göre istinaf kanun yoluna başvuru süresi kaç haftadır?","1 hafta","2 hafta","4 hafta","15 gün","1 ay","B","HMK m.345'e göre istinaf yoluna başvuru süresi ilk derece mahkemesi kararının tebliğinden itibaren 2 haftadır.","Kanun Yolları: İstinaf: 2 hafta içinde bölge adliye mahkemesine (HMK m.345). Temyiz: 2 hafta içinde Yargıtay'a (HMK m.361). Parasal sınırın altındaki kararlar kesindir."],
["Hukuk Yargılama Usulü","İhtiyati tedbir kararına itiraz süresi kaç gündür?","3 gün","5 gün","7 gün","10 gün","15 gün","C","HMK m.394'e göre ihtiyati tedbir kararının uygulanmasından veya kararın tebliğinden itibaren 1 hafta (7 gün) içinde itiraz edilebilir.","İhtiyati Tedbir: Dava açılmadan önce veya dava sırasında istenebilir. Karşı taraf dinlenmeden verilebilir (HMK m.390). İtiraz süresi 1 hafta. Tedbire muhalefetin yaptırımı disiplin hapsidir."],
["Hukuk Yargılama Usulü","Aşağıdakilerden hangisi kesin delillerden biridir?","Tanık","Bilirkişi","Keşif","Senet (belge)","Emsal karar","D","HMK m.200'e göre senetle ispat kuralı gereği senede bağlanması gereken hukuki işlemler ancak senetle ispat edilebilir. Senet kesin delildir.","Delil Türleri: Kesin deliller: senet, yemin, kesin hüküm. Takdiri deliller: tanık, bilirkişi, keşif, uzman görüşü. Senede karşı tanıkla ispat kural olarak mümkün değildir (HMK m.200-201)."],

// ===== ANAYASA YARGISI - 2 ek =====
["Anayasa Yargısı","Anayasa Mahkemesi'nin verdiği iptal kararı ne zaman yürürlüğe girer?","Hemen","Resmi Gazetede yayımlandığı tarihte","Karardan 6 ay sonra","TBMM onayıyla","Cumhurbaşkanı onayıyla","B","AY m.153/3'e göre iptal kararları gerekçesi yazılmadan açıklanamaz ve Resmi Gazetede yayımlandığı tarihte yürürlüğe girer. AYM yürürlük tarihini 1 yıla kadar erteleyebilir.","AYM Kararlarının Etkisi: Kararlar kesindir, geriye yürümez (AY m.153). Resmi Gazetede yayımlanır. Yürürlüğü 1 yıla kadar ertelenebilir. İptal edilen hüküm iptal kararının yayımı tarihinde yürürlükten kalkar."],
["Anayasa Yargısı","Bireysel başvuruda başvuru süresi ne kadardır?","15 gün","30 gün","60 gün","90 gün","1 yıl","B","6216 sayılı Kanun m.47/5'e göre bireysel başvurunun, başvuru yollarının tüketildiği tarihten itibaren 30 gün içinde yapılması gerekir.","Bireysel Başvuru Şartları: (1) Olağan kanun yollarının tüketilmesi, (2) 30 gün içinde başvuru, (3) Güncel ve kişisel hak ihlali, (4) AİHS kapsamındaki temel hak ve özgürlük ihlali."],

// ===== İDARİ YARGILAMA USULÜ - 2 ek =====
["İdari Yargılama Usulü","İdari yargıda dava açma süresi hangi andan itibaren başlar?","İşlemin yapıldığı tarih","Yazılı bildirimin yapıldığı tarih","İşlemin Resmi Gazetede yayımı","İşlemin uygulanması","İtiraz süresinin bitimi","B","İYUK m.7/2'ye göre süre yazılı bildirimin yapıldığı tarihi izleyen günden başlar. Düzenleyici işlemlerde ise ilan veya yayın tarihini izleyen günden başlar.","Dava Açma Süresinin Başlangıcı: Bireysel işlemlerde yazılı tebligat tarihi, düzenleyici işlemlerde ilan/yayım tarihi, eylemlerden doğan davalarda eylemin öğrenildiği tarih esas alınır."],
["İdari Yargılama Usulü","Danıştay'ın ilk derece mahkemesi olarak baktığı dava türü hangisidir?","Tüm iptal davaları","Cumhurbaşkanlığı kararnamelerine karşı açılan davalar","Belediye işlemlerine karşı davalar","Vergi davaları","Memur davaları","B","2575 sayılı Danıştay Kanunu m.24'e göre Danıştay, Cumhurbaşkanlığı kararnamelerine, bakanlıklar ile kamu kuruluşlarının müşterek çıkardıkları düzenleyici işlemlere karşı açılan davaları ilk derece mahkemesi olarak görür.","Danıştay'ın Görevleri: İlk derece: CBK'lara, bakanlık düzenleyici işlemlerine karşı davalar. Temyiz: bölge idare mahkemesi kararlarının temyizi. Danışma: Kanun tasarı ve teklifleri hakkında görüş bildirme."],

// ===== VERGİ HUKUKU - 3 ek =====
["Vergi Hukuku","Aşağıdakilerden hangisi dolaylı vergilerden biridir?","Gelir vergisi","Kurumlar vergisi","Katma değer vergisi (KDV)","Veraset ve intikal vergisi","Motorlu taşıtlar vergisi","C","KDV dolaylı (vasıtalı) bir vergidir; mal ve hizmetin fiyatına eklenerek tüketiciden tahsil edilir. Gelir ve kurumlar vergisi dolaysız (vasıtasız) vergilerdir.","Vergi Türleri: Dolaysız vergiler: Gelir vergisi, kurumlar vergisi, emlak vergisi. Dolaylı vergiler: KDV, ÖTV, damga vergisi. Dolaylı vergiler yansıtılabilir, son tüketici üzerinde kalır."],
["Vergi Hukuku","Vergi hukukunda idarenin re'sen vergi tarhı yetkisi hangi durumda kullanılır?","Her zaman","Beyanname verilmediğinde veya eksik verildiğinde","Sadece mahkeme kararıyla","Mükellefin talebiyle","Vergi dairesi müdürünün takdiriyle","B","VUK m.30'a göre re'sen tarh, beyanname verilmemesi, defter kayıtlarına güvenilmemesi veya matrah takdiri gerektiren hallerde uygulanır.","Vergi Tarhı Usulleri: (1) Beyana dayanan tarh, (2) İkmalen tarh (matrah farkı), (3) Re'sen tarh (beyanname verilmemesi/eksiklik), (4) Verginin idarece tarhı. Re'sen tarhta takdir komisyonu devreye girer."],
["Vergi Hukuku","Vergi mahkemesinde dava açma süresi kaç gündür?","15 gün","30 gün","60 gün","90 gün","7 gün","B","İYUK m.7'ye göre vergi mahkemelerinde dava açma süresi 30 gündür. İdare mahkemelerinde ise bu süre 60 gündür.","Vergi Yargılaması: Dava açma süresi 30 gün. Vergi/cezayı kaldırma davası vergi mahkemesinde açılır. Dava açmak verginin tahsilini durdurur (otomatik yürütme durdurma)."],

// ===== VERGİ USUL HUKUKU - 4 ek =====
["Vergi Usul Hukuku","VUK'a göre mücbir sebep halinde vergi ödevlerinin yerine getirilme süresi ne olur?","Kısalır","Durur (işlemez)","İki katına çıkar","Değişmez","Sona erer","B","VUK m.15'e göre mücbir sebep halinde süre işlemez. Mücbir sebep: ağır hastalık, yangın, yer sarsıntısı, sel gibi afetler, kişinin iradesi dışındaki sebeplerdir.","Mücbir Sebep (VUK m.13): Ağır kaza/hastalık, tutukluluk, yangın/deprem/su baskını, kişinin iradesi dışında meydana gelen engeller. Süre mücbir sebebin kalktığı günden itibaren yeniden işlemeye başlar."],
["Vergi Usul Hukuku","Aşağıdakilerden hangisi VUK'ta düzenlenen kaçakçılık suçlarının yaptırımıdır?","Adli para cezası","Hapis cezası","İdari para cezası","Vergi ziyaı cezası","Usulsüzlük cezası","B","VUK m.359'a göre kaçakçılık suçları hapis cezasıyla cezalandırılır. Defter ve belge gizleme, sahte fatura düzenleme/kullanma bu kapsamdadır.","Vergi Cezaları: İdari cezalar: vergi ziyaı cezası, usulsüzlük cezası, özel usulsüzlük cezası. Adli ceza: kaçakçılık suçu (hapis cezası, VUK m.359). Vergi ziyaı: verginin zamanında tahakkuk ettirilmemesi/eksik tahakkuk."],
["Vergi Usul Hukuku","Düzeltme ve şikayet yolu nedir?","Vergi mahkemesine başvuru","Vergi hatalarının idari yoldan düzeltilmesi","Danıştay'a temyiz","Ombudsmana başvuru","Anayasa Mahkemesine başvuru","B","VUK m.116-126'ya göre vergi hatalarının (hesap hataları ve vergilendirme hataları) düzeltilmesi vergi dairesinden talep edilir. Red halinde Hazine ve Maliye Bakanlığına şikayet yoluyla başvurulur.","Düzeltme-Şikayet: Vergi hataları vergi dairesince re'sen veya talep üzerine düzeltilir. Düzeltme talebi reddedilirse 30 gün içinde şikayet yoluyla Bakanlığa başvurulur. Şikayet de reddedilirse dava açılabilir."],
["Vergi Usul Hukuku","VUK'a göre aşağıdakilerden hangisi vergilendirme hatalarından biridir?","Matrah hatası","Mükellefin şahsında hata","Hesap hatası","Miktar hatası","Toplama hatası","B","VUK m.118'e göre vergilendirme hataları: mükellefin şahsında hata, mükellefiyette hata, mevzuda hata, vergilendirme veya muafiyet döneminde hatadır. Hesap, matrah ve toplama hataları hesap hatalarıdır.","Vergi Hataları: Hesap hataları (VUK m.117): matrah hatası, vergi miktarında hata, çifte vergilendirme. Vergilendirme hataları (VUK m.118): mükellefin şahsında, mükellefiyette, mevzuda, dönemde hata."],

// ===== AVUKATLIK HUKUKU - 3 ek =====
["Avukatlık Hukuku","Avukatın azledilmesi halinde ücret hakkı ne olur?","Ücret hakkı tamamen düşer","Ücretin tamamına hak kazanır","Yarı ücret alır","Orantılı ücret alır","Sadece masrafları alır","B","Avukatlık Kanunu m.174'e göre avukatın azli halinde ücretin tamamı verilir. Avukatın haklı nedenle çekilmesi halinde de ücretin tamamına hak kazanılır.","Avukatlık Ücreti: Azil halinde ücretin tamamı ödenir (AK m.174). Haksız azilde ücretin tamamı + tazminat istenebilir. Avukatın haklı istifasında da ücret hakkı doğar."],
["Avukatlık Hukuku","Avukatlar hangi kuruluşun zorunlu üyesidir?","Türkiye Barolar Birliği","Bölgedeki baro","Adalet Bakanlığı","Hukuk Derneği","Avukatlar Odası","B","Avukatlık Kanunu m.66'ya göre her avukat levhasına yazıldığı baronun üyesidir. Baro üyeliği zorunludur. Barolar TBB'nin üyesidir.","Baro ve TBB: Avukatlar bulundukları il barosuna kaydolur. Her ilde bir baro bulunur. Barolar TBB'nin üyesidir. TBB, baroların ve avukatların üst kuruluşudur."],
["Avukatlık Hukuku","Aşağıdakilerden hangisi avukatlığa kabul şartlarından biri değildir?","TC vatandaşı olmak","Hukuk fakültesi mezunu olmak","En az 25 yaşında olmak","Avukatlık stajını tamamlamak","HMGS'yi geçmek","C","Avukatlık Kanunu m.3'te yaş şartı 25 değildir. Şartlar: TC vatandaşlığı, hukuk fakültesi mezuniyeti, staj tamamlama, engel hal bulunmaması ve HMGS başarısı.","Avukatlığa Kabul Şartları (AK m.3): (1) TC vatandaşı, (2) Hukuk fakültesi mezunu, (3) Avukatlık stajını tamamlama, (4) Ceza mahkumiyeti/disiplin engeli olmama, (5) HMGS başarısı. Yaş sınırı yoktur."],

// ===== HUKUK FELSEFESİ VE SOSYOLOJİSİ - 4 ek =====
["Hukuk Felsefesi ve Sosyolojisi","Hukuki pozitivizmin temel savı nedir?","Hukuk doğadan gelir","Hukuk devlet tarafından konulan normlardır","Hukuk ahlaka dayanır","Hukuk dinden doğar","Hukuk gelenekten türer","B","Hukuki pozitivizm, hukukun kaynağını devlet iradesinde (yasama organı) görür. Kelsen'in saf hukuk teorisi bu akımın en önemli örneğidir.","Hukuki Pozitivizm: Hukuk = devlet tarafından konulan kurallar. Temsilciler: Austin (hukuk=egemenin emri), Kelsen (saf hukuk teorisi, normlar hiyerarşisi), Hart (kabul kuralı). Doğal hukuktan ayrılır."],
["Hukuk Felsefesi ve Sosyolojisi","Hans Kelsen'in normlar hiyerarşisi piramidinde en üstte ne yer alır?","Kanunlar","Anayasa","Temel norm (Grundnorm)","Yönetmelikler","Uluslararası antlaşmalar","C","Kelsen'e göre tüm hukuk normlarının geçerliliği üst norma dayanır ve piramiddin tepesinde varsayılan temel norm (Grundnorm) bulunur.","Kelsen'in Normlar Hiyerarşisi: Temel norm (Grundnorm) → Anayasa → Kanunlar → Yönetmelikler → Bireysel işlemler. Her norm geçerliliğini bir üst normdan alır. Temel norm varsayılandır."],
["Hukuk Felsefesi ve Sosyolojisi","Sosyolojik hukuk yaklaşımının kurucusu sayılan düşünür kimdir?","Kelsen","Eugen Ehrlich","Montesquieu","Savigny","Austin","B","Eugen Ehrlich 'yaşayan hukuk' kavramını geliştirerek hukukun toplumsal gerçekliğe dayandığını savunmuş ve hukuk sosyolojisinin kurucusu kabul edilmiştir.","Hukuk Sosyolojisi: Ehrlich - 'yaşayan hukuk' (devlet hukukunun ötesinde toplumsal kurallar). Duguit - toplumsal dayanışma. Pound - 'menfaatlerin dengelenmesi'. Weber - hukukun rasyonelleşmesi."],
["Hukuk Felsefesi ve Sosyolojisi","Adalet kavramının 'herkese hakkını vermek' şeklindeki tanımı kime aittir?","Aristoteles","Platon","Ulpianus","Cicero","Hobbes","C","Romalı hukukçu Ulpianus adaleti 'suum cuique tribuere' (herkese hakkını vermek) olarak tanımlamıştır. Bu tanım dağıtıcı adalet anlayışının temelini oluşturur.","Adalet Türleri: Denkleştirici adalet (düzeltici): eşitler arası eşitlik. Dağıtıcı adalet: herkese hakkı olanın verilmesi (Aristoteles). Ulpianus: 'Iustitia est constans et perpetua voluntas ius suum cuique tribuendi.'"],

// ===== TÜRK HUKUK TARİHİ - 4 ek =====
["Türk Hukuk Tarihi","Türk Medeni Kanunu (TMK) hangi yıl kabul edilmiştir?","1920","1924","1926","1928","1930","C","4 Ekim 1926'da İsviçre Medeni Kanunu esas alınarak Türk Medeni Kanunu kabul edilmiş ve 4 Ekim 1926'da yürürlüğe girmiştir. 2001'de yenilenerek 4721 sayılı TMK kabul edildi.","TMK Tarihi: 1926'da İsviçre MK'dan iktibas edildi. Laik hukuk düzenine geçişin en önemli adımı. 2001'de modernize edildi (4721 sayılı Kanun). Kadın-erkek eşitliği, edinilmiş mallara katılma rejimi getirildi."],
["Türk Hukuk Tarihi","Tanzimat Fermanı hangi yıl ilan edilmiştir?","1808","1839","1856","1876","1908","B","Tanzimat Fermanı (Gülhane Hatt-ı Hümayunu) 3 Kasım 1839'da ilan edilmiştir. Osmanlı'da hukuk reformlarının başlangıcı kabul edilir.","Tanzimat Dönemi: 1839 Tanzimat Fermanı → can, mal, namus güvencesi, kanun önünde eşitlik. 1856 Islahat Fermanı → gayrimüslim hakları. 1876 Kanun-i Esasi → ilk anayasa. Mecelle bu dönemde hazırlandı."],
["Türk Hukuk Tarihi","Osmanlı'da ilk anayasa olan Kanun-i Esasi hangi yıl ilan edilmiştir?","1839","1856","1876","1908","1921","C","23 Aralık 1876'da II. Abdülhamit döneminde Kanun-i Esasi (Temel Kanun) ilan edilmiştir. Osmanlı'nın ilk ve tek anayasasıdır.","Kanun-i Esasi (1876): Osmanlı'nın ilk anayasası. Mebusan Meclisi ve Ayan Meclisi kuruldu. Padişahın meclisi fesih yetkisi vardı. 1878'de meclis tatil edildi, 1908 II. Meşrutiyet ile yeniden toplandı."],
["Türk Hukuk Tarihi","1921 Anayasası'nın (Teşkilat-ı Esasiye) en belirgin özelliği nedir?","Kuvvetler ayrılığı ilkesi","Laiklik ilkesi","Egemenliğin kayıtsız şartsız millete ait olması","Çok partili sistem","Federal devlet yapısı","C","1921 Anayasası m.1: 'Hakimiyet bilâ kayd ü şart milletindir.' Milli egemenlik ilkesi ilk kez bu anayasada kabul edilmiştir. Kuvvetler birliği ilkesi benimsenmiştir.","1921 Anayasası: Olağanüstü dönem anayasası, 23 madde. Milli egemenlik, kuvvetler birliği (meclis hükümeti sistemi). Laiklik ilkesi yoktu. 1923'te cumhuriyet ilan edildi ve anayasaya eklendi."],

// ===== MİLLETLERARASI HUKUK - 4 ek =====
["Milletlerarası Hukuk","Uluslararası Adalet Divanı nerede bulunur?","New York","Cenevre","Lahey","Brüksel","Strasbourg","C","UAD, Hollanda'nın Lahey kentinde bulunur. BM'nin yargı organıdır. 15 hakimden oluşur, görev süresi 9 yıldır.","Uluslararası Adalet Divanı: BM'nin asli yargı organı. Lahey'de bulunur. 15 hakim, 9 yıl görev süresi. Devletler arası uyuşmazlıkları çözer. Bireyler dava açamaz. Kararları bağlayıcıdır."],
["Milletlerarası Hukuk","Uluslararası antlaşmaların hukuki rejimini düzenleyen temel sözleşme hangisidir?","BM Antlaşması","1969 Viyana Antlaşmalar Hukuku Sözleşmesi","Lahey Sözleşmesi","Cenevre Sözleşmeleri","Roma Statüsü","B","1969 Viyana Antlaşmalar Hukuku Sözleşmesi, devletler arası antlaşmaların akdedilmesi, yürürlüğe girmesi, yorumu, geçersizliği ve sona ermesi konularını düzenler.","Antlaşmalar Hukuku: 1969 Viyana Sözleşmesi temel kaynaktır. Pacta sunt servanda (ahde vefa) ilkesi esastır. Antlaşmalar: onay, katılma veya imza ile bağlayıcı hale gelir. Çekince koyma hakkı vardır."],
["Milletlerarası Hukuk","Jus cogens (emredici norm) ne anlama gelir?","Örf ve adet hukuku kuralı","Hiçbir sapmanın mümkün olmadığı genel uluslararası hukuk normu","BM Güvenlik Konseyi kararı","İkili antlaşma hükmü","Uluslararası teamül","B","1969 Viyana Sözleşmesi m.53'e göre jus cogens normları, uluslararası toplumun bütünü tarafından kabul edilen ve sapılması mümkün olmayan üstün normlardır (soykırım yasağı, kölelik yasağı vb.).","Jus Cogens: Sapma kabul etmeyen üstün normlar. Örnekler: soykırım yasağı, işkence yasağı, kölelik yasağı, saldırı yasağı. Jus cogens'e aykırı antlaşma geçersizdir (batıl)."],
["Milletlerarası Hukuk","Devletlerin tanınması hukuki açıdan ne tür bir işlemdir?","Kurucu işlem","Açıklayıcı işlem","Her ikisi de olabilir","Yasama işlemi","Yargısal işlem","C","Devletlerin tanınmasının hukuki niteliği tartışmalıdır. Kurucu (constitutif) teoriye göre tanıma devleti yaratır; açıklayıcı (dekleratif) teoriye göre sadece mevcut durumu tespit eder.","Devletin Tanınması: Kurucu teori: tanıma devletlik sıfatını verir. Açıklayıcı teori: devlet unsurları varsa tanıma sadece tespittir. Montevideo Sözleşmesi (1933): halk, ülke, hükümet, diğer devletlerle ilişki kurma kapasitesi."],

// ===== MİLLETLERARASI ÖZEL HUKUK - 4 ek =====
["Milletlerarası Özel Hukuk","MÖHUK'a göre haksız fiilden doğan borç ilişkisine hangi hukuk uygulanır?","Türk hukuku","Failin milli hukuku","Haksız fiilin işlendiği yer hukuku","Zarar görenin milli hukuku","Mahkeme hukuku","C","MÖHUK m.34'e göre haksız fiilden doğan borç ilişkilerine haksız fiilin işlendiği yer hukuku uygulanır.","MÖHUK Bağlama Kuralları: Haksız fiil → işlendiği yer hukuku. Sözleşme → tarafların seçtiği hukuk (yoksa en sıkı ilişkili hukuk). Ayni haklar → malın bulunduğu yer hukuku. Miras → milli hukuk."],
["Milletlerarası Özel Hukuk","Yabancı mahkeme kararlarının Türkiye'de icra edilebilmesi için gerekli olan işlem nedir?","Doğrudan icra","Tenfiz kararı","Tanıma kararı","Temyiz","Tercüme","B","MÖHUK m.50'ye göre yabancı mahkeme kararlarının Türkiye'de icrası için yetkili Türk mahkemesinden tenfiz kararı alınması gerekir.","Tanıma ve Tenfiz: Tanıma: yabancı kararın kesin hüküm/delil etkisi. Tenfiz: yabancı kararın icra edilebilir hale getirilmesi. Tenfiz şartları: karşılıklılık, kamu düzenine aykırı olmama, savunma hakkının ihlal edilmemiş olması."],
["Milletlerarası Özel Hukuk","Kamu düzeni müdahalesi (ordre public) ne demektir?","Yabancı hukukun her zaman uygulanması","Türk hukukunun temel ilkelerine aykırı yabancı hukukun uygulanmaması","Uluslararası antlaşmaların üstünlüğü","Devletlerin egemenlik hakkı","Yargı bağımsızlığı","B","MÖHUK m.5'e göre yetkili yabancı hukukun uygulanması Türk kamu düzenine açıkça aykırı ise uygulanmaz, Türk hukuku uygulanır.","Kamu Düzeni: Yabancı hukukun uygulanmasının Türk toplumunun temel değerlerine açıkça aykırı düşmesi halinde devreye girer. İstisna niteliğindedir, dar yorumlanır. Somut sonuca bakılır (sonuç odaklı)."],
["Milletlerarası Özel Hukuk","Türk vatandaşlığının kazanılma yollarından biri aşağıdakilerden hangisidir?","Yalnızca doğumla","Yalnızca evlenmeyle","Doğumla veya sonradan kazanma","Yalnızca başvuruyla","İkamet izniyle otomatik","C","5901 sayılı TVK'ya göre vatandaşlık doğumla (soy bağı veya doğum yeri esası) veya sonradan (yetkili makam kararı, evlat edinme, seçme hakkı) kazanılır.","Vatandaşlık Kazanma: Doğumla: soy bağı (anne/babadan) + doğum yeri. Sonradan: yetkili makam kararı (başvuru + şartlar), evlenme (3 yıl + başvuru), evlat edinme (küçükler). Çifte vatandaşlık mümkündür."],

// ===== GENEL KAMU HUKUKU - 4 ek =====
["Genel Kamu Hukuku","Montesquieu'nun kuvvetler ayrılığı teorisinde üç kuvvet nedir?","Yasama, yürütme, yargı","Yasama, yürütme, denetim","Devlet, hükümet, yargı","Meclis, cumhurbaşkanı, mahkeme","Halk, meclis, hükümet","A","Montesquieu 'Kanunların Ruhu' adlı eserinde devlet iktidarını yasama, yürütme ve yargı olarak üçe ayırmış ve bunların farklı organlara verilmesini savunmuştur.","Kuvvetler Ayrılığı: Montesquieu (1748) - iktidarın kötüye kullanılmasını önlemek için yasama, yürütme ve yargı ayrı organlara verilmelidir. Denge ve denetim (checks and balances) sistemi bu teoriye dayanır."],
["Genel Kamu Hukuku","Devletin unsurları nelerdir?","Halk, ülke (toprak), egemenlik","Halk, hükümet, ordu","Anayasa, meclis, mahkeme","Toprak, para birimi, bayrak","Hükümet, bürokrasi, yargı","A","Devletin üç temel (kurucu) unsuru vardır: insan topluluğu (halk), ülke (toprak parçası) ve egemenlik (üstün iktidar). Bu unsurlar olmadan devletten söz edilemez.","Devletin Unsurları: (1) İnsan unsuru (halk/millet), (2) Ülke unsuru (kara, deniz, hava), (3) Egemenlik (en üstün iktidar, iç ve dış egemenlik). Bazı yazarlar 4. unsur olarak hukuki düzeni ekler."],
["Genel Kamu Hukuku","Sosyal devlet ilkesinin anlamı nedir?","Devletin ekonomiye müdahale etmemesi","Devletin toplumsal eşitsizlikleri gidermeye çalışması","Devletin yalnızca güvenlik sağlaması","Devletin din kurallarını uygulaması","Devletin serbest piyasa ekonomisini koruması","B","Sosyal devlet, toplumsal adaleti sağlamak, gelir dağılımındaki dengesizlikleri gidermek ve herkes için insan onuruna yaraşır asgari yaşam koşullarını temin etmekle yükümlü devlettir.","Sosyal Devlet: AY m.2'de belirtilen Cumhuriyetin niteliklerinden biri. Amaçları: sosyal adalet, fırsat eşitliği, gelir dağılımında denge, sosyal güvenlik, asgari yaşam standardı. Araçları: vergi, sosyal yardım, eğitim, sağlık."],
["Genel Kamu Hukuku","Hukuk devleti ilkesinin temel gereklerinden biri aşağıdakilerden hangisidir?","Güçlü ordu","Tek parti yönetimi","Yargı bağımsızlığı","Monarşi","Sansür","C","Hukuk devletinde yönetim hukuka bağlıdır ve bağımsız yargı organları tarafından denetlenir. Yargı bağımsızlığı hukuk devletinin vazgeçilmez unsurlarından biridir.","Hukuk Devleti İlkeleri: (1) Kanun önünde eşitlik, (2) Yargı bağımsızlığı, (3) Temel hak ve hürriyetlerin güvencesi, (4) İdarenin yargısal denetimi, (5) Kanuni hakim güvencesi, (6) Hukuki güvenlik ve belirlilik."],
];

module.exports = questions3;
