// HMGS Soru Bankası - Her dersten en az 10 soru (5 haftalık deneme için yeterli)
// Format: [subject, question, optA, optB, optC, optD, optE, correct, explanation, topicSummary]

const questions = [
// ===== MEDENİ HUKUK =====
["Medeni Hukuk","Türk Medeni Kanunu'na göre, ergin kılınma kararını aşağıdakilerden hangisi verir?","Sulh hukuk mahkemesi","Asliye hukuk mahkemesi","Aile mahkemesi","Vesayet makamı","Nüfus müdürlüğü","A","TMK m.12'ye göre ergin kılınma kararı, küçüğün yerleşim yeri sulh hukuk mahkemesi tarafından verilir. 15 yaşını dolduran küçük kendi isteğiyle, velinin rızasıyla mahkemece ergin kılınabilir.","Ergin Kılınma: TMK m.12 uyarınca 15 yaşını dolduran küçük, kendi isteği ve velisinin rızasıyla sulh hukuk mahkemesince ergin kılınabilir. Ergin kılınma kararı kesindir ve geri alınamaz."],
["Medeni Hukuk","Aşağıdakilerden hangisi kişiliğin sona erme hallerinden biri değildir?","Ölüm","Gaiplik kararı","Ölüm karinesi","Fiil ehliyetinin kaybı","Birlikte ölüm karinesi","D","Fiil ehliyetinin kaybedilmesi kişiliği sona erdirmez, sadece hukuki işlem yapma yetisini etkiler. Kişilik ölüm, gaiplik ve ölüm karinesi ile sona erer.","Kişiliğin Sona Ermesi: Kişilik üç şekilde sona erer: (1) Ölüm, (2) Gaiplik kararı (TMK m.32-35), (3) Ölüm karinesi (TMK m.31). Fiil ehliyetinin kaybı kişiliği sona erdirmez."],
["Medeni Hukuk","TMK'ya göre derneklerde genel kurul toplantısı en geç kaç yılda bir yapılmalıdır?","Her yıl","2 yılda bir","3 yılda bir","4 yılda bir","5 yılda bir","C","TMK m.74'e göre genel kurul en geç 3 yılda bir olmak üzere yönetim kurulunun çağrısı üzerine toplanır.","Dernek Genel Kurulu: TMK m.74 gereği dernek genel kurulu en geç üç yılda bir toplanmalıdır. Olağanüstü toplantı her zaman yapılabilir."],
["Medeni Hukuk","Taşınmaz mülkiyetinin kazanılması için aşağıdakilerden hangisi zorunludur?","Zilyetliğin devri","Tapu siciline tescil","Noterde düzenleme","Kadastro tespiti","Mahkeme kararı","B","TMK m.705'e göre taşınmaz mülkiyetinin kazanılması tescille olur. Miras, mahkeme kararı, cebri icra ve kamulaştırma gibi istisnai hallerde mülkiyet tescilden önce kazanılır.","Taşınmaz Mülkiyeti: Kural olarak tapu siciline tescil ile kazanılır (TMK m.705). İstisnalar: miras, mahkeme kararı, cebri icra, kamulaştırma ve kanunda öngörülen diğer haller."],
["Medeni Hukuk","Aşağıdakilerden hangisi sınırlı ayni haklardan biri değildir?","İrtifak hakkı","Rehin hakkı","Taşınmaz yükü","Mülkiyet hakkı","İntifa hakkı","D","Mülkiyet hakkı sınırlı değil tam ayni haktır. Sınırlı ayni haklar: irtifak hakları, taşınmaz yükü ve rehin haklarıdır.","Ayni Haklar: Tam ayni hak mülkiyettir. Sınırlı ayni haklar üçe ayrılır: (1) İrtifak hakları (intifa, oturma, geçit), (2) Rehin hakları (ipotek, taşınır rehni), (3) Taşınmaz yükü."],
["Medeni Hukuk","Kazandırıcı zamanaşımı ile taşınmaz mülkiyetinin kazanılması için gereken süre kaç yıldır?","5 yıl","10 yıl","15 yıl","20 yıl","25 yıl","D","TMK m.713'e göre olağanüstü kazandırıcı zamanaşımı süresi 20 yıldır. Tapusuz taşınmazları davasız ve aralıksız 20 yıl malik sıfatıyla zilyetinde bulunduran kişi tescil talebinde bulunabilir.","Kazandırıcı Zamanaşımı: Olağanüstü zamanaşımı ile kazanma 20 yıl (TMK m.713); olağan zamanaşımı ile kazanma 10 yıldır (TMK m.712)."],
["Medeni Hukuk","Vesayet altındaki kişinin yerleşim yeri neresidir?","Vasinin yerleşim yeri","Vesayet dairesinin bulunduğu yer","Kendi seçtiği yer","Son ikametgahı","Doğum yeri","B","TMK m.21/2'ye göre vesayet altındaki kişilerin yerleşim yeri, bağlı oldukları vesayet makamının bulunduğu yerdir.","Yerleşim Yeri: Velayet altındaki çocuğun yerleşim yeri ana-babasının yerleşim yeridir (TMK m.21/1). Vesayet altındakilerin yerleşim yeri vesayet makamının bulunduğu yerdir (TMK m.21/2)."],
["Medeni Hukuk","Evlenme başvurusu yapıldıktan sonra evlenme en geç ne kadar süre içinde yapılmalıdır?","3 ay","6 ay","1 yıl","45 gün","2 ay","B","TMK m.139'a göre evlenme, başvuru tarihinden itibaren 6 ay içinde yapılmazsa başvuru geçersiz hale gelir ve yeni bir başvuru gerekir.","Evlenme Başvurusu: Evlendirme memuruna başvurulduktan sonra 6 ay içinde evlenme gerçekleştirilmelidir (TMK m.139). Aksi halde başvuru hükümsüz kalır."],
["Medeni Hukuk","Aşağıdakilerden hangisi kesin evlenme engellerinden biridir?","Bekleme süresi (iddet müddeti)","Küçüklük","Akıl hastalığı","Yasal temsilcinin izni","Bulaşıcı hastalık","C","Akıl hastalığı kesin (mutlak) evlenme engelidir. Bekleme süresi, küçüklük ve yasal temsilci izni kesin olmayan (nispî) engellerdir.","Evlenme Engelleri: Kesin engeller: akıl hastalığı, hısımlık, evli olma. Kesin olmayan engeller: bekleme süresi, küçüklük, yasal temsilci izni."],
["Medeni Hukuk","TMK'ya göre miras bırakanın saklı paylı mirasçısı aşağıdakilerden hangisi değildir?","Altsoy","Anne-baba","Sağ kalan eş","Kardeşler","Evlatlık","D","TMK m.505-506'ya göre saklı paylı mirasçılar: altsoy, ana-baba ve sağ kalan eştir. Kardeşler saklı paylı mirasçı değildir.","Saklı Pay: Saklı paylı mirasçılar ve oranları: Altsoy için yasal payın 1/2'si, ana-baba için yasal payın 1/4'ü, sağ kalan eş için (altsoy veya ana-baba ile birlikte) yasal payın tamamı."],

// ===== BORÇLAR HUKUKU =====
["Borçlar Hukuku","TBK'ya göre genel zamanaşımı süresi kaç yıldır?","1 yıl","2 yıl","5 yıl","10 yıl","15 yıl","D","TBK m.146'ya göre kanunda aksine bir hüküm bulunmadıkça her alacak 10 yıllık zamanaşımına tabidir.","Zamanaşımı Süreleri: Genel zamanaşımı 10 yıl (TBK m.146). Kira, hizmet sözleşmesi, otel-yiyecek-içecek alacakları gibi belli alacaklarda 5 yıl (TBK m.147)."],
["Borçlar Hukuku","Haksız fiilden doğan tazminat davasında zamanaşımı süresi fiil ve failin öğrenilmesinden itibaren kaç yıldır?","1 yıl","2 yıl","3 yıl","5 yıl","10 yıl","B","TBK m.72'ye göre haksız fiil zamanaşımı, zarar görenin zararı ve tazminat yükümlüsünü öğrendiği tarihten itibaren 2 yıl ve her halde fiilin işlendiği tarihten itibaren 10 yıldır.","Haksız Fiil Zamanaşımı: Kısa süre 2 yıl (fiil ve failin öğrenilmesinden), uzun süre 10 yıl (fiilin işlenmesinden). Ceza zamanaşımı daha uzunsa o süre uygulanır (TBK m.72)."],
["Borçlar Hukuku","Aşağıdakilerden hangisi borcu sona erdiren hallerden biri değildir?","İfa","İbra","Takas","Zamanaşımı","Tecil","E","Tecil (erteleme) borcu sona erdirmez, sadece ifasını erteler. İfa, ibra, yenileme, takas, birleşme, ifa imkansızlığı borcu sona erdiren sebeplerdir.","Borcun Sona Ermesi: Borç şu sebeplerle sona erer: İfa, ibra, yenileme (tecdit), alacaklı-borçlu sıfatının birleşmesi, takas, borçlunun iflası ve zamanaşımı. Tecil borcu sona erdirmez."],
["Borçlar Hukuku","Müteselsil borçlulukta alacaklı borcun tamamını aşağıdakilerden hangisinden isteyebilir?","Yalnızca asıl borçludan","Borçluların herhangi birinden","Payları oranında her borçludan","Yalnızca kefil olan borçludan","Sadece ilk borçludan","B","TBK m.162'ye göre müteselsil borçlulukta alacaklı, borcun tamamını borçluların herhangi birinden talep edebilir. İç ilişkide borçlular payları oranında birbirlerine rücu ederler.","Müteselsil Borçluluk: Alacaklı borcun tamamını herhangi bir borçludan isteyebilir (TBK m.162). Ödeme yapan borçlu, diğerlerine rücu hakkına sahiptir (TBK m.167)."],
["Borçlar Hukuku","TBK'ya göre sözleşme serbestisi ilkesinin sınırlarından biri aşağıdakilerden hangisidir?","Dürüstlük kuralı","Mücbir sebep","Kusur sorumluluğu","Haksız fiil","Vekaletsiz iş görme","A","TBK m.27'ye göre kanunun emredici hükümlerine, ahlaka, kamu düzenine, kişilik haklarına aykırı veya konusu imkânsız olan sözleşmeler kesin hükümsüzdür.","Sözleşme Serbestisi: Taraflar kanun çerçevesinde diledikleri sözleşmeyi kurabilir. Sınırlar: Emredici hükümler, ahlak, kamu düzeni, kişilik hakları ve imkânsızlık (TBK m.26-27)."],
["Borçlar Hukuku","Cezai şart nedir?","Sözleşmeye aykırılık halinde ödenmesi kararlaştırılan para","Temerrüt faizi","Manevi tazminat","Gecikme cezası","Hapis cezası","A","TBK m.179'a göre cezai şart, borçlunun borcunu hiç veya gereği gibi ifa etmemesi halinde alacaklıya ödemeyi taahhüt ettiği bağımsız bir edimdir.","Cezai Şart: Seçimlik cezai şart: alacaklı ya ifayı ya cezayı ister. İfaya eklenen cezai şart: alacaklı hem ifayı hem cezayı isteyebilir. Dönme cezası: borçlu cezayı ödeyerek sözleşmeden dönebilir (TBK m.179-182)."],
["Borçlar Hukuku","Sebepsiz zenginleşmede geri verme borcu ne zaman doğar?","Zenginleşmenin gerçekleştiği anda","Karşı tarafın temerrüde düştüğünde","Dava açıldığında","Zenginleşenin kötüniyetli olduğu anda","Mahkeme kararıyla","A","TBK m.77'ye göre haklı neden olmaksızın bir başkasının malvarlığından zenginleşen, bunu geri vermekle yükümlüdür. Borç zenginleşme anında doğar.","Sebepsiz Zenginleşme: Şartları: (1) Bir tarafın zenginleşmesi, (2) Diğer tarafın fakirleşmesi, (3) İlliyet bağı, (4) Haklı sebebin bulunmaması. İyiniyetli zenginleşen yalnızca elinde kalanı iade eder."],
["Borçlar Hukuku","Aşağıdakilerden hangisi geçersizlik hallerinden biri olan 'iptal edilebilirlik' sebebidir?","Konunun imkansız olması","Yanılma (hata)","Kanuna aykırılık","Ahlaka aykırılık","Ehliyetsizlik","B","Yanılma (hata), aldatma ve korkutma iptal edilebilirlik (düzelebilir geçersizlik) sebepleridir. Bunlar irade bozukluğu halleridir ve TBK m.30-39'da düzenlenmiştir.","Geçersizlik: Kesin hükümsüzlük (butlan): konunun imkansızlığı, kanuna/ahlaka aykırılık. İptal edilebilirlik: yanılma, aldatma, korkutma. İrade sakatlığı halinde 1 yıl içinde sözleşme iptal edilebilir."],
["Borçlar Hukuku","Kira sözleşmesinde kiracının temerrüdü halinde kiraya veren yazılı bildirimle kaç gün süre vermelidir?","10 gün","15 gün","30 gün","60 gün","7 gün","C","TBK m.315'e göre konut ve çatılı iş yeri kiralarında kiracıya en az 30 günlük süre verilmelidir. Diğer kira ilişkilerinde bu süre 10 gündür.","Kiracı Temerrüdü: Konut/çatılı iş yeri kirasında 30 gün, diğer kiralarda 10 gün süre verilir (TBK m.315). Süre sonunda ödeme yapılmazsa kiraya veren sözleşmeyi feshedebilir."],
["Borçlar Hukuku","TBK'ya göre vekalet sözleşmesinde vekilin temel borcu nedir?","Sonuç garantisi vermek","Özen gösterme ve sadakat borcu","Bedel ödeme","Teminat gösterme","Risk üstlenme","B","TBK m.506'ya göre vekilin temel borcu, vekalet konusu işi özenle ve müvekkilin yararını gözeterek (sadakatle) yürütmektir.","Vekalet Sözleşmesi: Vekilin borçları: (1) Talimata uyma, (2) Özenli davranma, (3) Sadakat, (4) Hesap verme. Müvekkilin borçları: (1) Ücret ödeme, (2) Masrafları karşılama, (3) Vekili borçlardan kurtarma."],

// ===== TİCARET HUKUKU =====
["Ticaret Hukuku","TTK'ya göre anonim şirketin kurulması için en az kaç pay sahibi gerekir?","1","2","3","5","7","A","6102 sayılı TTK m.338'e göre anonim şirket tek kişi tarafından kurulabilir. Eski kanundaki 5 kişi şartı kaldırılmıştır.","Anonim Şirket Kuruluşu: TTK m.338 ile tek kişilik anonim şirket kurulabilir. Sermayesi en az 50.000 TL (kayıtlı sermaye sisteminde 100.000 TL) olmalıdır. Pay senetleri hamiline veya nama yazılı olabilir."],
["Ticaret Hukuku","Limited şirketin asgari sermaye tutarı ne kadardır?","10.000 TL","25.000 TL","50.000 TL","100.000 TL","250.000 TL","A","TTK m.580'e göre limited şirketin esas sermayesi en az 10.000 TL olmalıdır. Ortakların payları en az 25 TL veya katları olmalıdır.","Limited Şirket: Asgari sermaye 10.000 TL (TTK m.580). En çok 50 ortak olabilir. Ortaklar sınırlı sorumludur. Hisse senetleri çıkaramaz, sadece pay senedi çıkarabilir."],
["Ticaret Hukuku","Ticari defterlerin sahibi lehine delil olarak kabul edilebilmesi için aşağıdaki şartlardan hangisi aranır?","Defterlerin noter tasdikli olması","Defterlerin eksiksiz ve usulüne uygun tutulması","Karşı tarafın defterlerinin de incelenmesi","Hepsinin birlikte gerçekleşmesi","Yalnızca noter tasdiki yeterlidir","D","Ticari defterlerin sahibi lehine delil olabilmesi için defterlerin usulüne uygun tutulması, noter tasdikli olması ve karşı tarafın defterlerinin de incelenmesi gerekir.","Ticari Defterler: Tacirler yevmiye defteri, defteri kebir ve envanter defteri tutmak zorundadır. Defterlerin delil niteliği TTK m.64-88'de düzenlenmiştir."],
["Ticaret Hukuku","Aşağıdakilerden hangisi kıymetli evrak türlerinden biri değildir?","Bono","Poliçe","Çek","Makbuz","Emre yazılı senet","D","Makbuz bir ödeme belgesidir, kıymetli evrak değildir. Kıymetli evrak: kambiyo senetleri (bono, poliçe, çek), hisse senetleri, konişmento vb.","Kıymetli Evrak: Hakkın senetten ayrı ileri sürülemediği ve devredilemediği belgelerdir. Üç türü: Nama yazılı, emre yazılı ve hamiline yazılı kıymetli evrak."],
["Ticaret Hukuku","TTK'ya göre tacir sıfatı kimin için geçerlidir?","Her ticari iş yapan","Bir ticari işletmeyi kısmen dahi olsa kendi adına işleten","Esnaf","Serbest meslek erbabı","Tüketici","B","TTK m.12'ye göre bir ticari işletmeyi kısmen dahi olsa kendi adına işleten kişi tacirdir. Esnaflar tacir sayılmaz.","Tacir Kavramı: Gerçek kişi tacir: ticari işletmeyi kendi adına işleten (TTK m.12). Tüzel kişi tacir: ticaret şirketleri (TTK m.16). Tacirin basiretli davranma yükümlülüğü vardır."],
["Ticaret Hukuku","Çekte muhatap kim olabilir?","Herhangi bir gerçek kişi","Herhangi bir tüzel kişi","Yalnızca bankalar","Yalnızca ticaret şirketleri","Noterler","C","TTK m.782'ye göre çekte muhatap yalnızca banka olabilir. Banka dışında bir kişi üzerine çekilen çek geçerli değildir.","Çek Hukuku: Çekte muhatap sadece bankadır (TTK m.782). İbraz süreleri: aynı yer 10 gün, farklı yer 1 ay, farklı ülke 3 ay. Karşılıksız çeke cezai yaptırım uygulanır."],
["Ticaret Hukuku","Ticari işlerde temerrüt faizi oranı nasıl belirlenir?","Yasal faiz oranı uygulanır","Sözleşme ile serbestçe belirlenir","T.C. Merkez Bankası avans faiz oranı uygulanır","Mahkeme takdir eder","Sabit %9 uygulanır","C","3095 sayılı Kanun m.2'ye göre ticari işlerde temerrüt faizi TCMB'nin kısa vadeli avans işlemleri için uyguladığı faiz oranına göre belirlenir.","Ticari Faiz: Ticari işlerde temerrüt faizi TCMB avans faiz oranıdır. Adi işlerde yasal faiz oranı uygulanır. Bileşik faiz (faize faiz) kural olarak yasaktır; istisnası cari hesap ve ticari kredidir."],
["Ticaret Hukuku","Haksız rekabette zamanaşımı süresi fiilin öğrenilmesinden itibaren kaç yıldır?","6 ay","1 yıl","2 yıl","3 yıl","5 yıl","B","TTK m.60'a göre haksız rekabet davası, fiilin öğrenilmesinden itibaren 1 yıl ve her halde fiilin işlenmesinden itibaren 3 yıl içinde zamanaşımına uğrar.","Haksız Rekabet: TTK m.54-63'te düzenlenmiştir. Zamanaşımı: kısa süre 1 yıl, uzun süre 3 yıl. Rakipler, müşteriler, mesleki birlikler ve ticaret odaları dava açabilir."],
["Ticaret Hukuku","TTK'ya göre anonim şirkette yönetim kurulu en az kaç kişiden oluşur?","1","2","3","5","7","A","TTK m.359'a göre anonim şirkette yönetim kurulu bir veya daha fazla kişiden oluşabilir. Tek kişilik yönetim kurulu mümkündür.","AŞ Yönetim Kurulu: En az 1 üyeden oluşur. Tüzel kişiler de üye olabilir. Görev süresi en çok 3 yıl. Genel kurul tarafından seçilir ve azledilebilir."],
["Ticaret Hukuku","Bonoda aşağıdaki unsurlardan hangisinin bulunmaması senedi geçersiz kılar?","Düzenleme yeri","Vade","Kayıtsız şartsız ödeme vaadi","Faiz oranı","Aval","C","TTK m.776'ya göre kayıtsız şartsız belirli bedeli ödeme vaadi bononun zorunlu unsurudur. Bulunmaması senedi bono sayılmasını engeller.","Bono Zorunlu Unsurları: (1) 'Bono/emre yazılı senet' kelimesi, (2) Kayıtsız şartsız ödeme vaadi, (3) Lehtar, (4) Düzenleme tarihi, (5) Düzenleyenin imzası. Eksiklik halinde senet bono sayılmaz."],

// ===== ANAYASA HUKUKU =====
["Anayasa Hukuku","1982 Anayasası'na göre Cumhurbaşkanının görev süresi kaç yıldır?","4 yıl","5 yıl","6 yıl","7 yıl","8 yıl","B","Anayasa m.101'e göre Cumhurbaşkanı 5 yıllık süre için seçilir ve en fazla iki defa seçilebilir.","Cumhurbaşkanlığı: Görev süresi 5 yıl (AY m.101). En fazla 2 kez seçilebilir. Halk tarafından seçilir. 40 yaşını doldurmuş, yükseköğretim görmüş TC vatandaşları aday olabilir."],
["Anayasa Hukuku","Aşağıdakilerden hangisi temel hak ve hürriyetlerin sınırlanmasında uyulması gereken ilkelerden biri değildir?","Kanunla sınırlama","Anayasanın sözüne uygunluk","Ölçülülük ilkesi","Çekirdek alana dokunmama","Cumhurbaşkanı onayı","E","Temel hak sınırlamaları: kanunla yapılmalı, Anayasanın sözüne ve ruhuna uygun olmalı, ölçülü olmalı, hakkın özüne dokunmamalıdır (AY m.13). Cumhurbaşkanı onayı aranmaz.","Temel Hak Sınırlama İlkeleri (AY m.13): (1) Kanunla sınırlama, (2) Anayasanın sözüne ve ruhuna uygunluk, (3) Ölçülülük, (4) Demokratik toplum düzeninin gereklerine uygunluk, (5) Hakkın özüne dokunmama."],
["Anayasa Hukuku","TBMM'nin toplantı yeter sayısı nedir?","Salt çoğunluk (301)","Üye tam sayısının 1/3'ü (200)","Üye tam sayısının 1/4'ü (150)","Üye tam sayısının 2/3'ü (400)","Üye tam sayısının 1/5'i (120)","B","Anayasa m.96'ya göre TBMM üye tamsayısının en az 1/3'ü (200 milletvekili) ile toplanır. Karar yeter sayısı ise toplantıya katılanların salt çoğunluğudur.","TBMM Toplantı ve Karar Sayıları: Toplantı yeter sayısı: 200 (1/3). Karar yeter sayısı: toplantıya katılanların salt çoğunluğu (ancak üye tam sayısının 1/4+1'inden az olamaz). Nitelikli çoğunluk: Anayasa değişikliği için 360 (3/5)."],
["Anayasa Hukuku","Olağanüstü hal ilan etme yetkisi kime aittir?","TBMM","Cumhurbaşkanı","Bakanlar Kurulu","Milli Güvenlik Kurulu","Genelkurmay Başkanı","B","Anayasa m.119'a göre olağanüstü hal ilan etme yetkisi Cumhurbaşkanına aittir. OHAL ilanı TBMM onayına sunulur.","OHAL (AY m.119): Cumhurbaşkanı tarafından ilan edilir ve TBMM'nin onayına sunulur. Süresi en fazla 6 ay. TBMM 4 ay olarak kısaltabilir, uzatabilir veya kaldırabilir."],
["Anayasa Hukuku","Anayasa Mahkemesi kaç üyeden oluşur?","9","11","13","15","17","D","Anayasa m.146'ya göre Anayasa Mahkemesi 15 üyeden oluşur. 12 üyeyi Cumhurbaşkanı, 3 üyeyi TBMM seçer.","Anayasa Mahkemesi: 15 üyeden oluşur. Görev süresi 12 yıl, yeniden seçilme yasağı var. 65 yaşını dolduranlar emekliye ayrılır. Başkan ve başkanvekili kendi üyeleri arasından seçilir."],
["Anayasa Hukuku","Aşağıdakilerden hangisi Cumhurbaşkanlığı Kararnamesi ile düzenlenemez?","Bakanlıkların kurulması","Temel haklar ve ödevler","Üst kademe yöneticilerinin atanması","Devlet teşkilatı","Kamu tüzel kişiliği kurulması","B","Anayasa m.104/17'ye göre temel haklar, kişi hakları ve siyasi haklar CBK ile düzenlenemez. Ayrıca kanunda açıkça düzenlenen konularda CBK çıkarılamaz.","CBK Sınırları: Temel haklar, kişi hakları, siyasi haklar, kanunla düzenlenmesi öngörülen konular ve kanunda açıkça düzenlenen konular CBK ile düzenlenemez."],
["Anayasa Hukuku","Bireysel başvuru hakkı hangi yıl Anayasaya eklenmiştir?","2004","2007","2010","2012","2017","C","2010 Anayasa değişikliği ile bireysel başvuru (anayasa şikâyeti) hakkı getirilmiş, 2012 yılında uygulamaya başlanmıştır.","Bireysel Başvuru: 2010 değişikliği ile AY m.148/3'e eklendi. Olağan kanun yollarının tükenmesi şarttır. 30 gün içinde yapılmalıdır. Temel hak ve özgürlüklerden AİHS kapsamındakiler için başvurulabilir."],
["Anayasa Hukuku","Anayasa değişikliği teklif edebilmek için en az kaç milletvekili gerekir?","50","100","150","200","301","D","Anayasa m.175'e göre Anayasanın değiştirilmesi TBMM üye tam sayısının en az 1/3'ü (200 milletvekili) tarafından yazıyla teklif edilebilir.","Anayasa Değişikliği: Teklif 200 milletvekili ile yapılır. Kabul: 360 oy ile kabul edilirse Cumhurbaşkanı halkoyuna sunabilir. 400 ve üzeri oy ile kabul edilirse doğrudan yayımlanır veya halkoyuna sunulabilir."],
["Anayasa Hukuku","Milletvekili dokunulmazlığının kaldırılması kararını kim verir?","Cumhurbaşkanı","Yargıtay","TBMM Genel Kurulu","Anayasa Mahkemesi","Adalet Bakanı","C","Anayasa m.83/2'ye göre milletvekili dokunulmazlığının kaldırılmasına TBMM Genel Kurulu karar verir.","Yasama Dokunulmazlığı: Milletvekilleri Meclis çalışmalarındaki oy ve sözlerinden sorumlu tutulamaz (sorumsuzluk). Seçimden önce veya sonra suç işlediği iddia edilen milletvekili, Meclis kararı olmadıkça tutulamaz (dokunulmazlık)."],
["Anayasa Hukuku","Laiklik ilkesi Anayasanın hangi maddesinde düzenlenmiştir?","Madde 1","Madde 2","Madde 3","Madde 4","Madde 5","B","Anayasa m.2'de Türkiye Cumhuriyetinin nitelikleri sayılmıştır. Laiklik bu niteliklerden biridir ve m.4 gereği değiştirilemez.","Cumhuriyetin Nitelikleri (AY m.2): Demokratik, laik, sosyal hukuk devleti. Bu nitelikler AY m.4 gereği değiştirilemez ve değiştirilmesi teklif dahi edilemez. AY m.1 (devletin şekli), m.2 (nitelikleri) ve m.3 (bütünlüğü, dili, bayrağı vb.) değiştirilmesi teklif edilemeyecek hükümlerdir."],

// ===== İDARE HUKUKU =====
["İdare Hukuku","İdari işlemlerin yargısal denetiminde genel görevli mahkeme hangisidir?","Asliye hukuk mahkemesi","İdare mahkemesi","Danıştay","Bölge idare mahkemesi","Vergi mahkemesi","B","2577 sayılı İYUK m.2'ye göre idari işlemlere karşı açılan iptal ve tam yargı davalarında genel görevli mahkeme idare mahkemesidir.","İdari Yargı Teşkilatı: İlk derece: İdare mahkemeleri (genel görevli) ve vergi mahkemeleri (vergi uyuşmazlıkları). İstinaf: Bölge idare mahkemeleri. Temyiz: Danıştay. Danıştay aynı zamanda bazı davalarda ilk derece mahkemesidir."],
["İdare Hukuku","İdari işlemin iptal davasında dava açma süresi kaç gündür?","15 gün","30 gün","60 gün","90 gün","1 yıl","C","İYUK m.7'ye göre idare mahkemelerinde dava açma süresi 60 gündür. Vergi mahkemelerinde bu süre 30 gündür.","İptal Davası Süreleri: İdare mahkemesinde 60 gün, vergi mahkemesinde 30 gün (İYUK m.7). Süre yazılı bildirimin yapıldığı günün ertesi gününden başlar."],
["İdare Hukuku","Aşağıdakilerden hangisi idarenin düzenleyici işlemlerinden biridir?","Atama kararı","Disiplin cezası","Yönetmelik","İdari para cezası","Ruhsat verilmesi","C","Yönetmelik genel ve soyut nitelikte bir düzenleyici işlemdir. Atama, disiplin cezası, para cezası ve ruhsat bireysel işlemlerdir.","İdari İşlem Türleri: Düzenleyici işlemler (genel-soyut): Tüzük, yönetmelik, genelge, tebliğ. Bireysel işlemler (özel-somut): Atama, disiplin cezası, ruhsat. Düzenleyici işlemler Resmi Gazetede yayımlanır."],
["İdare Hukuku","Kamu görevlilerinin görevleri sebebiyle verdikleri zararlardan dolayı tazminat davası kime karşı açılır?","Doğrudan kamu görevlisine","İdareye karşı","Hem idareye hem görevliye","Devlete karşı","Yargıya","B","Anayasa m.129/5 ve AY m.40/3 gereği kamu görevlilerinin yetkilerini kullanırken verdikleri zararlardan dolayı tazminat davası idare aleyhine açılır. İdare rücu hakkına sahiptir.","İdarenin Mali Sorumluluğu: Kamu görevlisine doğrudan dava açılamaz, dava idare aleyhine açılır (AY m.129/5). İdare, tazminat ödedikten sonra kusurlu görevliye rücu edebilir."],
["İdare Hukuku","İdari sözleşmelerde uyuşmazlık hangi yargı kolunda çözülür?","Adli yargı","İdari yargı","Anayasa yargısı","Uyuşmazlık mahkemesi","Tahkim","B","İdari sözleşmelerden doğan uyuşmazlıklar idari yargıda (idare ve vergi mahkemeleri, Danıştay) çözülür.","İdari Sözleşmeler: İmtiyaz, kamu hizmeti, müşterek emanet, iltizam ve idari hizmet sözleşmeleri idari sözleşmelerdir. Uyuşmazlıkları idari yargıda çözülür."],
["İdare Hukuku","Aşağıdakilerden hangisi merkezi yönetimin taşra teşkilatı birimlerinden biridir?","Belediye","İl özel idaresi","Valilik","Köy","Mahalle","C","Valilik merkezi yönetimin taşra teşkilatıdır. Belediye ve il özel idaresi yerinden yönetim kuruluşlarıdır. Köy de yerel yönetimdir.","Merkezi Yönetim Taşra Teşkilatı: İl yönetimi (vali), ilçe yönetimi (kaymakam), bucak yönetimi. Vali il genel idaresinin başıdır ve Cumhurbaşkanı tarafından atanır."],
["İdare Hukuku","İdarenin kusursuz sorumluluğu hangi ilkelere dayanır?","Kusur sorumluluğu","Risk ve fedakarlığın denkleştirilmesi","Sözleşme sorumluluğu","Haksız fiil","Vekaletsiz iş görme","B","İdarenin kusursuz sorumluluğu risk (tehlike) ilkesi ve fedakarlığın denkleştirilmesi (kamu külfetleri karşısında eşitlik) ilkesine dayanır.","Kusursuz Sorumluluk: Risk ilkesi: Tehlikeli faaliyetlerden doğan zararlar (silah kullanma, patlayıcı madde). Fedakarlığın denkleştirilmesi: Kamu yararına yapılan faaliyetlerin bireyde yarattığı özel zarar."],
["İdare Hukuku","Yürütmenin durdurulması kararı verilebilmesi için hangi şartların birlikte gerçekleşmesi gerekir?","Acillik ve ciddiyet","İdari işlemin açıkça hukuka aykırılığı ve telafisi güç zarar","Davalının kabul etmesi","Üst mahkeme onayı","Cumhurbaşkanı izni","B","İYUK m.27'ye göre yürütmenin durdurulması için (1) idari işlemin uygulanması halinde telafisi güç veya imkânsız zararların doğması ve (2) idari işlemin açıkça hukuka aykırı olması şartlarının birlikte gerçekleşmesi gerekir.","Yürütmenin Durdurulması: İki şart birlikte aranır: (1) Telafisi güç veya imkânsız zarar, (2) Açıkça hukuka aykırılık (İYUK m.27). YD kararları gerekçeli olmalıdır."],
["İdare Hukuku","Kamulaştırma bedelinin tespitini kim yapar?","İdare","Belediye encümeni","Asliye hukuk mahkemesi","İdare mahkemesi","Danıştay","C","2942 sayılı Kamulaştırma Kanunu m.10'a göre kamulaştırma bedelinin tespiti asliye hukuk mahkemesi tarafından yapılır.","Kamulaştırma: Kamu yararı amacıyla özel mülkiyetteki taşınmazın bedeli ödenerek idareye geçirilmesidir. Bedel tespiti asliye hukuk mahkemesince yapılır. Acele kamulaştırmada el koyma öncedir."],
["İdare Hukuku","İdari vesayet yetkisi ne anlama gelir?","Hiyerarşik denetim","Merkezi idarenin yerinden yönetim kuruluşları üzerindeki denetimi","Yargısal denetim","Siyasi denetim","Ombudsman denetimi","B","İdari vesayet, merkezi yönetimin yerinden yönetim kuruluşları (belediye, il özel idaresi, üniversite vb.) üzerindeki hukuka uygunluk ve yerindelik denetimidir.","İdari Vesayet: Merkezi yönetimin yerel yönetimler ve hizmet kuruluşları üzerindeki denetimidir. Hiyerarşiden farkı: ast-üst ilişkisi yoktur, kanunla düzenlenmiş sınırlı bir denetimdir."],

// ===== CEZA HUKUKU =====
["Ceza Hukuku","TCK'ya göre ceza sorumluluğunun kişiselliği ilkesi ne anlama gelir?","Ceza yalnızca faile verilir","Ceza ailesine de uygulanır","Tüzel kişilere ceza verilir","Suça iştirak edenler cezasızdır","Mağdurun rızası cezayı kaldırır","A","TCK m.20'ye göre ceza sorumluluğu şahsidir. Kimse başkasının fiilinden dolayı sorumlu tutulamaz. Tüzel kişiler hakkında ceza yaptırımı uygulanamaz, güvenlik tedbiri uygulanabilir.","Ceza Sorumluluğunun Kişiselliği (TCK m.20): Kimse başkasının fiilinden dolayı cezalandırılamaz. Tüzel kişilere ceza verilemez ancak güvenlik tedbiri (müsadere, iznin iptali) uygulanabilir."],
["Ceza Hukuku","Meşru müdafaa (meşru savunma) hangi hukuka uygunluk nedenlerinden biridir?","Kanun hükmünü yerine getirme","Hakkın kullanılması","Meşru savunma","İlgilinin rızası","Zorunluluk hali","C","TCK m.25/1'e göre gerek kendisine gerek başkasına yönelmiş haksız bir saldırıyı defetmek için saldırıyla orantılı biçimde işlenen fiillerden dolayı faile ceza verilmez.","Meşru Savunma (TCK m.25/1): Şartları - Saldırıya ilişkin: (1) haksız saldırı, (2) saldırı güncel olmalı, (3) bir hakka yönelmeli. Savunmaya ilişkin: (1) zorunluluk, (2) saldırıyla orantılılık."],
["Ceza Hukuku","Aşağıdakilerden hangisi cezayı azaltan şahsi sebeplerdendir?","Haksız tahrik","Meşru savunma","Kanun hükmü","Zorunluluk hali","Cebir ve tehdit","A","TCK m.29'a göre haksız bir fiilin meydana getirdiği hiddet veya şiddetli elemin etkisi altında suç işlenirse haksız tahrik indirimi uygulanır. Bu şahsi bir indirim sebebidir.","Haksız Tahrik (TCK m.29): Haksız bir fiilin meydana getirdiği hiddet veya şiddetli elemin etkisi altında suç işlenmesi halinde ağırlaştırılmış müebbet yerine 18-24 yıl, müebbet yerine 12-18 yıl, diğer cezalarda 1/4-3/4 oranında indirim yapılır."],
["Ceza Hukuku","TCK'ya göre suça teşebbüste ceza nasıl belirlenir?","Tamamlanmış suçun cezası verilir","İndirim uygulanır","Ceza verilmez","İki katı ceza verilir","Alt sınırdan ceza verilir","B","TCK m.35'e göre suça teşebbüs halinde meydana gelen zarar veya tehlikenin ağırlığına göre tamamlanmış suça ait cezada indirim yapılır.","Suça Teşebbüs (TCK m.35): Suçun icra hareketlerine başlanıp elde olmayan nedenlerle tamamlanamamasıdır. Ceza: Ağırlaştırılmış müebbette 13-20 yıl, müebbette 9-15 yıl, diğerlerinde cezanın 1/4-3/4 oranında indirilmesi."],
["Ceza Hukuku","Kanunilik ilkesinin sonuçlarından biri aşağıdakilerden hangisidir?","Kıyas yasağı","Takdiri indirim","Şahsi cezasızlık","Uzlaşma","Hükmün açıklanmasının geri bırakılması","A","TCK m.2'ye göre kanunilik ilkesi gereği suç ve cezada kıyas yapılamaz. Kanunların suç ve ceza içeren hükümlerinin uygulanmasında kıyas yapılamaz, bu hükümler genişletilerek yorumlanamaz.","Kanunilik İlkesi (TCK m.2): Sonuçları - (1) Suçta ve cezada kanun ilkesi, (2) Kıyas yasağı, (3) Geriye yürüme yasağı (lehe kanun hariç), (4) İdarenin düzenleyici işlemleriyle suç ve ceza konulamaz, (5) Belirlilik."],
["Ceza Hukuku","Taksirle adam öldürme suçunun cezası nedir?","1-3 yıl hapis","2-6 yıl hapis","3-8 yıl hapis","5-10 yıl hapis","Adli para cezası","B","TCK m.85'e göre taksirle bir insanın ölümüne neden olan kişi 2 yıldan 6 yıla kadar hapis cezası ile cezalandırılır.","Taksirle Öldürme (TCK m.85): Ceza 2-6 yıl hapis. Birden fazla kişinin ölümüne veya ölümle birlikte yaralanmaya neden olunması halinde 2-15 yıl hapis. Bilinçli taksirde ceza 1/3-1/2 oranında artırılır."],
["Ceza Hukuku","Aşağıdakilerden hangisi güvenlik tedbirlerinden biridir?","Hapis cezası","Adli para cezası","Müsadere","Haksız tahrik indirimi","Erteleme","C","TCK m.54-60'a göre müsadere (eşya ve kazanç müsaderesi) bir güvenlik tedbiridir. Hapis ve adli para cezası ise ceza türleridir.","Güvenlik Tedbirleri: (1) Belli hakları kullanmaktan yoksun bırakılma, (2) Müsadere (eşya/kazanç), (3) Çocuklara özgü güvenlik tedbirleri, (4) Akıl hastalarına özgü güvenlik tedbirleri, (5) Tüzel kişilere özgü güvenlik tedbirleri."],
["Ceza Hukuku","İçtima kurallarından 'zincirleme suç' ne demektir?","Birden fazla kişiye aynı anda zarar verme","Bir suç işleme kararının icrası kapsamında aynı suçun birden fazla kez işlenmesi","İki farklı suçun aynı anda işlenmesi","Suça iştirak","Suça teşebbüs","B","TCK m.43'e göre bir suç işleme kararının icrası kapsamında değişik zamanlarda bir kişiye karşı aynı suçun birden fazla işlenmesi zincirleme suçtur.","Zincirleme Suç (TCK m.43): Aynı suçun bir suç işleme kararı kapsamında birden fazla kez işlenmesidir. Ceza 1/4-3/4 oranında artırılır. Aynı suçun birden fazla kişiye karşı tek fiille işlenmesi de 43/2 kapsamındadır."],
["Ceza Hukuku","TCK'da 'olası kast' nasıl tanımlanır?","Sonucu isteme","Sonucun gerçekleşebileceğini öngörme ve kabul etme","Sonucu öngörememe","Dikkat ve özen yükümlülüğüne aykırı davranma","Bilinçli ihmal","B","TCK m.21/2'ye göre olası kast, kişinin suçun kanuni tanımındaki unsurların gerçekleşebileceğini öngörmesine rağmen fiili işlemesi, sonucu kabullenmesidir.","Kast Türleri: Doğrudan kast: sonucu bilme ve isteme. Olası kast: sonucu öngörme ve kabul etme (ceza 1/3-1/2 indirilir). Taksir: sonucu öngörememe. Bilinçli taksir: öngörme ama istememe."],
["Ceza Hukuku","Suçun unsurları aşağıdakilerden hangisidir?","Maddi - manevi - hukuka aykırılık","Sadece maddi unsur","Kast ve taksir","Fiil ve netice","Hareket ve zarar","A","Suçun üç temel unsuru vardır: (1) Maddi unsur (fiil, netice, nedensellik bağı), (2) Manevi unsur (kast veya taksir), (3) Hukuka aykırılık unsuru.","Suçun Unsurları: Maddi unsur: hareket, netice, illiyet bağı. Manevi unsur: kast (doğrudan/olası) veya taksir (basit/bilinçli). Hukuka aykırılık: hukuka uygunluk nedeni yoksa fiil hukuka aykırıdır."],
];

module.exports = questions;
