// HMGS Soru Bankası Part 2 - Kalan dersler
const questions2 = [
// ===== CEZA MUHAKEMESİ USULÜ =====
["Ceza Muhakemesi Usulü","CMK'ya göre tutukluluk süresi ağır ceza mahkemesinin görevine giren işlerde en çok ne kadardır?","6 ay","1 yıl","2 yıl","3 yıl","5 yıl","C","CMK m.102/2'ye göre ağır ceza mahkemesinin görevine giren işlerde tutukluluk süresi en çok 2 yıldır. Zorunlu hallerde 3 yıl daha uzatılabilir.","Tutukluluk Süreleri: Ağır ceza: en çok 2 yıl (uzatmayla 5 yıl). Diğer suçlar: en çok 1 yıl (uzatmayla 1.5 yıl). CMK m.102."],
["Ceza Muhakemesi Usulü","Aşağıdakilerden hangisi koruma tedbirlerinden biri değildir?","Yakalama","Tutuklama","Arama","Haksız tahrik","Elkoyma","D","Haksız tahrik bir ceza indirimi sebebidir, koruma tedbiri değildir. Koruma tedbirleri: yakalama, gözaltı, tutuklama, arama, elkoyma, teknik takip vb.","Koruma Tedbirleri: Yakalama, gözaltı, tutuklama, adli kontrol, arama, elkoyma, iletişimin tespiti, gizli soruşturmacı, teknik araçlarla izleme. Hâkim kararı veya gecikmesinde sakınca bulunan hallerde savcı emri gerekir."],
["Ceza Muhakemesi Usulü","Savcının kovuşturmaya yer olmadığına dair kararına karşı hangi yola başvurulur?","İstinaf","Temyiz","İtiraz","Şikayet","Karar düzeltme","C","CMK m.173'e göre kovuşturmaya yer olmadığına dair karara karşı sulh ceza hakimliğine itiraz edilebilir. İtiraz süresi kararın tebliğinden itibaren 15 gündür.","Kovuşturmaya Yer Olmadığı Kararı: 15 gün içinde sulh ceza hakimliğine itiraz edilir (CMK m.173). Hakimlik soruşturmanın genişletilmesini isteyebilir veya iddianame düzenlenmesini emredebilir."],
["Ceza Muhakemesi Usulü","İddianamenin iadesi kararını kim verir?","Cumhuriyet savcısı","Sulh ceza hakimi","Mahkeme (görevli mahkeme)","Bölge adliye mahkemesi","Yargıtay","C","CMK m.174'e göre iddianamenin iadesine görevli mahkeme karar verir. 15 gün içinde iade edilmeyen iddianame kabul edilmiş sayılır.","İddianamenin İadesi: Mahkeme 15 gün içinde eksiklik tespit ederse iddianameyi iade edebilir (CMK m.174). İade sebepleri: eksik soruşturma, usule aykırılık, suç unsurlarının oluşmaması."],
["Ceza Muhakemesi Usulü","Uzlaşma kapsamındaki suçlarda uzlaşma teklifi kim tarafından yapılır?","Hakim","Savcı","Uzlaştırmacı","Avukat","Mağdur","C","CMK m.253'e göre uzlaştırma işlemleri uzlaştırmacı tarafından yürütülür. Savcı dosyayı uzlaştırma bürosuna gönderir, uzlaştırmacı taraflara teklif yapar.","Uzlaşma: Soruşturma evresinde savcı, kovuşturma evresinde mahkeme uzlaştırma yoluna başvurur. Uzlaştırmacı 30 gün içinde (en fazla 20 gün uzatmayla) sonuçlandırır (CMK m.253-255)."],

// ===== İCRA VE İFLAS HUKUKU =====
["İcra ve İflas Hukuku","İlamsız icra takibinde borçlunun ödeme emrine itiraz süresi kaç gündür?","5 gün","7 gün","10 gün","15 gün","30 gün","B","İİK m.62'ye göre borçlu ödeme emrinin tebliğinden itibaren 7 gün içinde itiraz edebilir. İtiraz takibi durdurur.","Ödeme Emrine İtiraz: Süre 7 gündür. İtiraz icra dairesine yapılır. İtiraz ile takip durur. Alacaklı itirazın kaldırılması (icra mahkemesi) veya iptali (genel mahkeme) yollarına başvurabilir."],
["İcra ve İflas Hukuku","Aşağıdakilerden hangisi haczi caiz olmayan mallardan biridir?","Borçlunun maaşının 1/4'ü","Lüks eşyalar","Ticari mallar","Borçlunun ve ailesinin geçimi için zorunlu eşyalar","Taşınmazlar","D","İİK m.82'ye göre borçlu ve ailesinin hayatı için lüzumlu eşyalar haczedilemez. Bunlar arasında yatak, yemek takımı gibi zorunlu ev eşyaları sayılır.","Haczi Caiz Olmayan Mallar (İİK m.82): Zorunlu ev eşyaları, meslek ve sanat araçları, çiftçinin zorunlu aletleri, borçlunun haline münasip evi (meskeniyet iddiası), şahsa bağlı haklar."],
["İcra ve İflas Hukuku","İflas davası hangi mahkemede açılır?","İcra mahkemesi","Asliye ticaret mahkemesi","Asliye hukuk mahkemesi","Sulh hukuk mahkemesi","İdare mahkemesi","B","İİK m.154'e göre iflas davası borçlunun muamele merkezinin bulunduğu yerdeki asliye ticaret mahkemesinde açılır.","İflas Yolları: (1) Takipli iflas - ödeme emri → itiraz etmeme/itirazın kaldırılması → iflas davası (2) Takipsiz (doğrudan) iflas - belli şartlarda doğrudan asliye ticaret mahkemesinde dava açma."],
["İcra ve İflas Hukuku","Menfi tespit davası ne zaman açılır?","İcra takibinden önce veya sonra","Yalnızca takipten önce","Yalnızca takipten sonra","İflas kararından sonra","Hacizden sonra","A","İİK m.72'ye göre menfi tespit davası icra takibinden önce veya sonra açılabilir. Takipten önce açılırsa %15 teminat karşılığı ihtiyati tedbir istenebilir.","Menfi Tespit ve İstirdat: Borçlu olmadığını ispat için menfi tespit davası açılır. Borç ödendikten sonra geri almak için istirdat davası açılır. Süre 1 yıl (İİK m.72)."],
["İcra ve İflas Hukuku","Konkordato mühleti en fazla ne kadar süreyle verilebilir?","3 ay","6 ay","1 yıl","17 ay + 6 ay uzatma = 23 ay","2 yıl","D","İİK m.289'a göre geçici mühlet 3 ay (2 ay uzatmayla 5 ay), kesin mühlet 1 yıl (6 ay uzatmayla 18 ay). Toplam süre 23 ayı geçemez.","Konkordato: Borçlunun mali durumunun düzeltilmesi için alacaklılarla anlaşma yoludur. Geçici mühlet: 3+2=5 ay. Kesin mühlet: 12+6=18 ay. Toplam en fazla 23 ay."],

// ===== İŞ VE SOSYAL GÜVENLİK HUKUKU =====
["İş ve Sosyal Güvenlik Hukuku","İş Kanunu'na göre deneme süresi en fazla kaç aydır?","1 ay","2 ay","3 ay","4 ay","6 ay","B","4857 sayılı İK m.15'e göre deneme süresi en çok 2 aydır. Toplu iş sözleşmesiyle 4 aya kadar uzatılabilir. Deneme süresinde fesih bildirim sürelerine uyma zorunluluğu yoktur.","Deneme Süresi: En çok 2 ay, TİS ile 4 ay (İK m.15). Bu süre içinde taraflar bildirimsiz ve tazminatsız feshedebilir. SGK bildirimi deneme süresinden itibaren yapılır."],
["İş ve Sosyal Güvenlik Hukuku","Kıdem tazminatı hakkı doğması için asgari çalışma süresi ne kadardır?","6 ay","1 yıl","2 yıl","3 yıl","5 yıl","B","1475 sayılı İK m.14'e göre kıdem tazminatı hakkının doğması için işçinin en az 1 yıl çalışmış olması gerekir.","Kıdem Tazminatı: En az 1 yıl çalışma şartı. Her tam yıl için 30 günlük brüt ücret. Fesih şekli önemlidir: haklı fesih, emeklilik, kadın işçinin evlenmesi halinde hak doğar. İstifa halinde kural olarak hak doğmaz."],
["İş ve Sosyal Güvenlik Hukuku","İşe iade davası kaç gün içinde açılmalıdır?","7 gün","15 gün","30 gün","60 gün","1 ay","D","İK m.20'ye göre fesih bildiriminin tebliğinden itibaren 1 ay (30 gün) içinde arabulucuya başvurulmalıdır. Arabuluculuk sonuçsuz kalırsa 2 hafta içinde dava açılır.","İşe İade: Arabuluculuk zorunlu ön şart. 30 gün içinde arabulucuya başvuru, anlaşılamazsa 2 hafta içinde dava. Şartlar: 30+ işçi çalışan iş yeri, 6 ay kıdem, belirsiz süreli sözleşme."],
["İş ve Sosyal Güvenlik Hukuku","Fazla çalışma ücreti normal saatten yüzde kaç fazla ödenir?","25","30","40","50","75","D","İK m.41'e göre fazla çalışma ücretinin her bir saati için verilecek ücret, normal çalışma ücretinin saat başına düşen miktarının %50 yükseltilmesiyle ödenir.","Fazla Çalışma: Haftalık 45 saati aşan çalışma fazla çalışmadır. Ücret %50 zamlı ödenir. Yıllık fazla çalışma 270 saati geçemez. Serbest zaman: her 1 saat fazla çalışma için 1.5 saat serbest zaman."],
["İş ve Sosyal Güvenlik Hukuku","SGK'ya göre yaşlılık aylığı bağlanması için asgari prim gün sayısı kaçtır?","3600","4500","5400","7200","9000","D","5510 sayılı Kanun m.28'e göre yaşlılık aylığı için en az 7200 gün prim ödenmiş olması gerekir (kademeli geçiş hükümleri saklıdır).","Yaşlılık Aylığı Şartları: (1) Yaş şartı (kademeli olarak artır), (2) Prim gün sayısı: en az 7200 gün (veya 25 yıl sigortalılık + 4500 gün), (3) İşten ayrılma ve SGK'ya başvuru."],

// ===== DİĞER DERSLER =====
["Anayasa Yargısı","Anayasa Mahkemesi'ne iptal davası açma yetkisi kimlere aittir?","Cumhurbaşkanı ve TBMM üye tamsayısının 1/5'i","Her milletvekili","Vatandaşlar","Mahkemeler","Barolar","A","AY m.150'ye göre iptal davası açma yetkisi Cumhurbaşkanı, TBMM üye tamsayısının 1/5'i (120 milletvekili) ve iktidar/ana muhalefet partisi meclis gruplarına aittir.","İptal Davası: Kanunların şekil bozukluğuna dayalı iptal davası 10 gün, esas yönünden 60 gün içinde açılır. CBK'lara karşı da iptal davası açılabilir."],
["Anayasa Yargısı","Anayasa Mahkemesi'nin Yüce Divan sıfatıyla yargıladığı kişiler arasında aşağıdakilerden hangisi yoktur?","Cumhurbaşkanı","Milletvekilleri","TBMM Başkanı","Bakanlar","Genelkurmay Başkanı","B","AY m.148/6'ya göre Yüce Divan'da yargılananlar: Cumhurbaşkanı, TBMM Başkanı, Cumhurbaşkanı yardımcıları, bakanlar, yüksek yargı organları başkan ve üyeleri, Genelkurmay Başkanı.","Yüce Divan: AYM Yüce Divan sıfatıyla görev yapar. Milletvekilleri Yüce Divan'da yargılanmaz, genel ceza mahkemelerinde yargılanır (dokunulmazlık kalktıktan sonra)."],
["Anayasa Yargısı","İtiraz yolu (somut norm denetimi) ne anlama gelir?","Vatandaşın AYM'ye başvurması","Mahkemenin davada uygulayacağı kanunun Anayasaya aykırılığını AYM'ye taşıması","Cumhurbaşkanının kanunu veto etmesi","TBMM'nin kanunu değiştirmesi","Ombudsmanın başvurusu","B","AY m.152'ye göre görülmekte olan davada uygulanacak kanun hükmünün Anayasaya aykırı olduğu kanısına varan mahkeme, AYM'ye başvurur. AYM 5 ay içinde karar verir.","İtiraz Yolu (AY m.152): Davada uygulanacak norm AY'ye aykırıysa mahkeme AYM'ye başvurur. 5 ay içinde karar verilmezse mahkeme yürürlükteki kanun hükümlerine göre davayı sonuçlandırır."],

["İdari Yargılama Usulü","İdari yargıda tam yargı davası ne amaçla açılır?","İdari işlemin iptali","İdarenin verdiği zararın tazmini","Normatif düzenlemenin iptali","İdari sözleşmenin feshi","Memuriyetin iadesi","B","İYUK m.2/1-b'ye göre tam yargı davası idari eylem ve işlemlerden doğan zararların tazminini amaçlar.","Tam Yargı Davası: İdarenin eylem ve işlemlerinden doğan zararların tazmini için açılır. İptal ve tam yargı davası birlikte açılabilir. İptal kararından sonra 60 gün içinde tam yargı davası açılabilir."],
["İdari Yargılama Usulü","İdari yargıda istinaf süresi kaç gündür?","7 gün","15 gün","30 gün","60 gün","90 gün","C","İYUK m.45'e göre idare ve vergi mahkemelerinin kararlarına karşı bölge idare mahkemelerine istinaf başvuru süresi 30 gündür.","İdari Yargıda Kanun Yolları: İstinaf: 30 gün içinde bölge idare mahkemesine. Temyiz: 30 gün içinde Danıştay'a (belli parasal sınırın üstünde). Karar düzeltme kaldırılmıştır."],
["İdari Yargılama Usulü","İdari yargıda duruşma yapılması zorunlu olan dava türü hangisidir?","İptal davası","Tam yargı davası","İptal ve tam yargı davaları","Vergi davaları","Hiçbiri - tarafların talebi gerekir","E","İYUK m.18'e göre idari yargıda kural olarak yazılı yargılama usulü uygulanır. Duruşma tarafların talebi veya mahkemenin re'sen kararı ile yapılır, zorunlu değildir.","İdari Yargılama Usulü İlkeleri: (1) Yazılılık (kural), (2) Re'sen araştırma, (3) İddia ve savunmanın genişletilmesi/değiştirilmesi yasağı yoktur, (4) Duruşma isteğe bağlıdır."],

["Vergi Hukuku","Vergi hukukunda kıyas yapılabilir mi?","Evet, her zaman","Hayır, kesinlikle yapılamaz","Sadece mükellef lehine yapılabilir","Sadece idare lehine","Danıştay izniyle yapılabilir","B","VUK m.3'e göre vergi kanunları lafzı ve ruhu ile hüküm ifade eder. Vergi hukukunda kıyas yasağı geçerlidir, bu kanunilik ilkesinin doğal sonucudur.","Verginin Kanuniliği: AY m.73/3 gereği vergi ancak kanunla konulur, değiştirilir veya kaldırılır. Kıyas yasağı bu ilkenin sonucudur. Yorum yöntemlerinden kıyas hariç hepsi kullanılabilir."],
["Vergi Hukuku","Aşağıdakilerden hangisi vergi borcunu sona erdiren nedenlerden biri değildir?","Ödeme","Zamanaşımı","Terkin","Uzlaşma","Tahakkuk","E","Tahakkuk vergi borcunu sona erdirmez, aksine vergi borcunun kesinleşmesidir. Sona erme nedenleri: ödeme, zamanaşımı, terkin, tahsil imkansızlığı, uzlaşma, yargı kararı.","Vergi Borcunun Sona Ermesi: (1) Ödeme, (2) Zamanaşımı (tarh zamanaşımı 5 yıl, tahsil zamanaşımı 5 yıl), (3) Terkin, (4) Uzlaşma, (5) Tahsil imkansızlığı, (6) Yargı kararı."],
["Vergi Usul Hukuku","VUK'a göre tarh zamanaşımı süresi kaç yıldır?","1 yıl","3 yıl","5 yıl","7 yıl","10 yıl","C","VUK m.114'e göre vergi alacağının doğduğu takvim yılını takip eden yılın başından başlayarak 5 yıl içinde tarh ve mükellefe tebliğ edilmeyen vergiler zamanaşımına uğrar.","Tarh Zamanaşımı: 5 yıl (VUK m.114). Vergiyi doğuran olayın gerçekleştiği yılı takip eden yılbaşından başlar. Takdir komisyonuna sevk zamanaşımını durdurur (en fazla 1 yıl)."],

["Avukatlık Hukuku","Avukatın sır saklama yükümlülüğü ne zaman sona erer?","Davanın bitmesiyle","Vekalet ilişkisinin sona ermesiyle","Hiçbir zaman sona ermez","Müvekkilin izniyle","5 yıl sonra","C","Avukatlık Kanunu m.36'ya göre avukatın sır saklama yükümlülüğü süresizdir. Vekalet ilişkisi sona erse bile devam eder.","Avukatın Yükümlülükleri: (1) Sır saklama (süresiz), (2) Çıkar çatışmasından kaçınma, (3) İşi özenle yürütme, (4) Müvekkili aydınlatma. Sır saklama yükümlülüğü kamu düzenine ilişkindir."],
["Avukatlık Hukuku","Avukatlık stajı süresi ne kadardır?","6 ay","1 yıl","18 ay","2 yıl","3 yıl","B","Avukatlık Kanunu m.15'e göre avukatlık stajı 1 yıldır. İlk 6 ay mahkeme ve adli kurumlarda, ikinci 6 ay bir avukatın yanında yapılır.","Avukatlık Stajı: Toplam 1 yıl. İlk 6 ay: mahkemeler, savcılık, icra daireleri. İkinci 6 ay: en az 5 yıllık avukatın yanında. Staj bitiminde baro levhasına yazılma ile avukatlık yetkisi kazanılır."],

["Hukuk Felsefesi ve Sosyolojisi","Doğal hukuk teorisine göre hukukun kaynağı nedir?","Devlet iradesi","İnsan aklı ve doğa","Toplumsal gelenek","Yargıç kararları","Ekonomik ilişkiler","B","Doğal hukuk teorisi, hukukun kaynağının devlet iradesi değil insan aklı ve doğanın kendisi olduğunu savunur. Evrensel ve değişmez ilkeler vardır.","Doğal Hukuk: Pozitif hukukun üstünde evrensel, akla dayanan kurallar vardır. Temsilcileri: Aristoteles, Aquinas, Grotius, Locke. Karşıtı: Hukuki pozitivizm (hukuk=devlet iradesi)."],

["Türk Hukuk Tarihi","Mecelle hangi padişah döneminde hazırlanmıştır?","II. Mahmut","Abdülmecit","Abdülaziz","II. Abdülhamit","V. Mehmet","C","Mecelle-i Ahkam-ı Adliye 1868-1876 yılları arasında Abdülaziz döneminde Ahmet Cevdet Paşa başkanlığındaki komisyon tarafından hazırlanmıştır.","Mecelle: 1868-1876 arasında hazırlandı. Hanefi fıkhına dayalı medeni kanun niteliğinde. 1851 madde, 16 kitap. Ahmet Cevdet Paşa başkanlığında hazırlandı. 1926'da TMK'nın kabulüyle yürürlükten kalktı."],

["Milletlerarası Hukuk","BM Güvenlik Konseyi'nin daimi üye sayısı kaçtır?","3","4","5","7","10","C","BM Güvenlik Konseyi 15 üyeden oluşur. 5'i daimi üyedir: ABD, Rusya, Çin, İngiltere, Fransa. Daimi üyelerin veto hakkı bulunur.","BM Güvenlik Konseyi: 5 daimi (veto hakkı olan) + 10 geçici üye = 15 üye. Kararlar 9 oyla alınır. Daimi üyenin olumsuz oyu veto sayılır. Barışı koruma, yaptırım kararları alır."],

["Milletlerarası Özel Hukuk","MÖHUK'a göre evlenme ehliyeti hangi hukuka tabidir?","Türk hukuku","Tarafların milli hukuku","Evlenme yeri hukuku","Mutad mesken hukuku","Seçilen hukuk","B","5718 sayılı MÖHUK m.13'e göre evlenme ehliyeti ve şartları taraflardan her birinin evlenme anındaki milli hukukuna tabidir.","MÖHUK'ta Bağlama Kuralları: Ehliyet → milli hukuk. Evlenme ehliyeti → milli hukuk. Boşanma → müşterek milli hukuk yoksa müşterek mutad mesken, yoksa Türk hukuku. Miras → milli hukuk."],

["Genel Kamu Hukuku","Egemenlik kavramının teorik temelini atan düşünür kimdir?","John Locke","Montesquieu","Jean Bodin","Rousseau","Machiavelli","C","Jean Bodin 'Devletin Altı Kitabı' (1576) adlı eserinde egemenliği mutlak ve sürekli iktidar olarak tanımlamıştır.","Egemenlik Teorisi: Bodin egemenliği 'mutlak ve sürekli iktidar' olarak tanımlamıştır. Rousseau halk egemenliğini savunmuştur. Modern devlette egemenlik halka aittir ve anayasa ile sınırlandırılmıştır."],
];

module.exports = questions2;
