-- Supabase SQL Editor için Gerekli Tablolar --

-- 1. Sorular Tablosu
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    question_text TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    option_e TEXT NOT NULL,
    correct_answer TEXT NOT NULL,
    explanation TEXT NOT NULL,
    topic_summary TEXT NOT NULL
);

-- 2. Haftalık Deneme Kayıtları
CREATE TABLE weekly_exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_number INTEGER NOT NULL,
    exam_number INTEGER NOT NULL,
    week_start TEXT NOT NULL,
    questions_json JSONB NOT NULL
);

-- 3. Kullanıcıların Çözdükleri Sınavların Sonuçları (Asla Silinmeyecek)
-- Yabancı anahtar (Foreign Key) YOK, çünkü eski denemeler silinse bile bu veriler kalmalı.
CREATE TABLE exam_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    exam_number INTEGER NOT NULL,   -- Sınav silinse bile kaçıncı deneme olduğu bilinsin
    week_start TEXT NOT NULL,       -- Hangi haftanın denemesi olduğu bilinsin
    score INTEGER NOT NULL,
    correct_count INTEGER NOT NULL,
    wrong_count INTEGER NOT NULL,
    empty_count INTEGER NOT NULL,
    answers_json JSONB,             -- Hangi soruya ne cevap verdiğinin kaydı
    total_time INTEGER,             -- Kaç saniyede çözdü
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Rastgele soru çekme fonksiyonu (Flashcards için)
CREATE OR REPLACE FUNCTION get_random_questions(limit_count integer)
RETURNS SETOF questions AS $$
BEGIN
    RETURN QUERY SELECT * FROM questions ORDER BY random() LIMIT limit_count;
END;
$$ LANGUAGE plpgsql;
